### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by wafabouzid** [Dobiasd/frugally-deep#122]
I want to install frugally deep without using cmake but I didn't understand how to use the links in the folder  zip 
[frugally-deep-master.zip](https://github.com/Dobiasd/frugally-deep/files/2868731/frugally-deep-master.zip

**Comment by Dobiasd** [comment]
So your question is: How to use a header only library in C++.

Since this is nothing special to frugally-deep, I'd suggest you read up on this.

In general: Extract the zip file to some directory and then add it as an additional include directory for your C++ compiler. How to do this depends on which compiler or IDE you are using.

**Comment by wafabouzid** [comment]
i'm using Qt creator 5.4

Le ven. 15 févr. 2019 à 11:26, Tobias Hermann <notifications@github.com> a
écrit :

**Comment by Dobiasd** [comment]
OK. I've never used this IDE, but a quick google search for "qt creator include path" gives enough promising results.

And since this here (issue section of frugally-deep) is not the right place to teach C++ basics, I'll close the issue.
