### ISSUE TITLE
I suggest to remove direct dependency in keras in the python scripts and move to tensorflow

### ISSUE THREAD

**Issue by LevLavy** [Dobiasd/frugally-deep#17]
For example in the converter use:

import tensorflow as tf
from tensorflow.contrib.keras.api.keras.models import load_model
from tensorflow.contrib.keras.api.keras.backend import backend as K

As keras is now part of tensorflow it will save another pip install.

**Comment by Dobiasd** [comment]
Good idea. I just tried and was able to convert `convert_model.py` successfully. However `save_application_examples.py` has [this problem](https://stackoverflow.com/questions/48810937/keras-tensorflow-does-not-find-weights-file-imagenet). But I guess this can be fixed somehow.

**Comment by Dobiasd** [comment]
I guess [`tensorflow.contrib.keras`](https://www.tensorflow.org/api_docs/python/tf/contrib/keras) is obsolete and it would be [`tensorflow.python.keras`](https://www.tensorflow.org/api_docs/python/tf/keras) instead, but that is just a minor detail.

However I will try to collect a second opinion on [`keras` vs. `tensorflow.python.keras`](https://www.reddit.com/r/KerasML/comments/7xs7hh/keras_vs_tensorflowpythonkeras_which_one_to_use/) before going forward with this transition.

**Comment by Dobiasd** [comment]
Small update. The weight-loading problem `save_application_examples.py` has with the switch will be [fixed in TensorFlow 1.6](https://github.com/tensorflow/tensorflow/issues/16683#issuecomment-363621409).

**Comment by LevLavy** [comment]
cool, no pressure. you can also allow to choose the import via configuration

**Comment by Dobiasd** [comment]
Just pushed a commit that replaces `import keras` with `import tensorflow.python.keras` in `convert_model.py`. In `save_application_examples.py` it is still `import keras` due to the bug in TensorFlow pre 1.6.0 as mentioned above. But the typical fdeep user will never have to use `save_application_examples.py`, it is just needed for running the unit tests.

For the sake of completeness: It's not just switching the `import`s, but with `tensorflow.python.keras` it is  `model._input_layers` instead of `model.input_layers` and `model._name` instead of `model.name`. However this difference is not consistent, e.g. `layer.name` is still `layer.name` and does not change to `layer._name`.

**Comment by Dobiasd** [comment]
For completeness: With the update to TensorFlow 1.6.0 I was able to [drop](https://github.com/Dobiasd/frugally-deep/commit/562349afe9c98cc6336120873738764d2bfa0c12) the external Keras completely as an dependency.

**Comment by Dobiasd** [comment]
fyi: It turned out `tensorflow.python.keras` is only some kind of second-class citizen. The normal `keras` library has some features earlier. So I switched back to `keras`.
