### ISSUE TITLE
result.hpp(316,1): error C2653: 'FOut': is not a class or namespace name

### ISSUE THREAD

**Issue by pligithub** [Dobiasd/frugally-deep#194]
Hi Tobias,

I am self taught (poorly) in coding, so please forgive me if I am making a simple mistake and asking a stupid question.

I am using VS 2019 and I have downloaded all the required libraries and extracted them to my hard drive. I have gone into the properties page for my VS project and added the correct paths for the #include files into the Include Directories field. When I try to run my program I get the following two errors:

1>c:\Users\phili\source\Ext Libs\FunctionalPlus-master\include\fplus\result.hpp(316,1): error C2653: 'FOut': is not a class or namespace name
1>c:\Users\phili\source\Ext Libs\FunctionalPlus-master\include\fplus\result.hpp(323,1): error C2653: 'FOut': is not a class or namespace name

I have spent several hours troubleshooting but I can't figure it out. If someone could point me in the correct direction it would be greatly appreciated.

**Comment by pligithub** [comment]
Sorry, I see this has already been reported in the FuntionalPlus issues section.

**Comment by Dobiasd** [comment]
Hi @pligithub,

> I am self taught (poorly) in coding, so please forgive me if I am making a simple mistake and asking a stupid question.

No worry. Many very good developers are self taught. And your question was not stupid. :)

> I have spent several hours troubleshooting but I can't figure it out.

Sorry for the trouble. I hope the rest of your journey with frugally-deep go more smoothly.

> Sorry, I see this has already been reported in the FuntionalPlus issues section.

For future readers of this issue here and for reference:
https://github.com/Dobiasd/FunctionalPlus/issues/159

In short: It is a [bug](https://developercommunity.visualstudio.com/content/problem/815759/compiler-bug-getting-c2563-error-on-version-1633.html) in the latest version of the MSVC compiler. It will be fixed in release 16.5 Preview 2.
