### ISSUE TITLE
Is there any plan to support Conv1D?

### ISSUE THREAD

**Issue by zhangzhishan** [Dobiasd/frugally-deep#2]
Do you have any plan to support Conv1D and keras 2.0?

**Comment by Dobiasd** [comment]
It's all based on Keras 2.x. Currently I'm working with 2.0.9.

Regarding `Conv1D`, together with `UpSampling1D`, `ZeroPadding1D`, `MaxPooling1D` and `AveragePooling1D` it is the next layer type I plan to implement. I will have a look at it during the next few days and get back to you.

**Comment by Dobiasd** [comment]
[Done](https://github.com/Dobiasd/frugally-deep/commit/c83be510724f8687441a4fbdfbeeaa2b731d235c). :-)

Since all these 1D operations are simply special cases of the 2D operations, it was not that hard to implement them. I [added extensive tests also for the 1D layers](https://github.com/Dobiasd/frugally-deep/blob/c83be510724f8687441a4fbdfbeeaa2b731d235c/keras_export/generate_test_models.py#L147), so they should work in your application as flawlessly as the 2D layers do.

In case you actually use the library for something, I would be very happy to hear about your experience.

**Comment by zhangzhishan** [comment]
I will try it. Thank you!
