### ISSUE TITLE
AssertionError in `show_batch_normalization_layer`

### ISSUE THREAD

**Issue by dschwertfeger** [Dobiasd/frugally-deep#200]
Hi Dobiasd,

I'm getting an `AssertionError` in `show_batch_normalization_layer`:

```python
assert layer_axis == -1 or layer_axis + 1 == len(layer.input_shape)
```
…where my 

- `layer_axis  = 1` and 
- `layer.input_shape = (None, 128, 32)`.

So, `len(layer.input_shape) = 3` (although the first dimension is the batch-dimension) and that is, of course, not `== 2`.

I don't really understand the purpose of this assertion in the first place, so I don't know what I need to change (if anything) to successfully convert my model. 

I'm using latest versions of everything, read the FAQ and checked existing (and closed issues.) I found _one_ similar issue (https://github.com/Dobiasd/frugally-deep/issues/109) but the discussion didn't directly address the `AssertionError` in `show_batch_normalization_layer`.

Minimal example:

```python
import numpy as np

from tensorflow.keras.layers import (Activation, BatchNormalization, Conv1D,
                                     Dense, Dropout, Flatten,
                                     GlobalAveragePooling1D, MaxPooling1D)
from tensorflow.keras.models import Sequential

def make_model(input_shape):
    model = Sequential()
    model.add(BatchNormalization(axis=1, input_shape=input_shape))
    model.add(Conv1D(filters=32, kernel_size=3))
    model.add(BatchNormalization())
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size=2))
    model.add(Flatten())
    model.add(Dense(64, activation='relu'))
    model.add(Dense(1, activation='softmax'))
    return model

input_shape = (128, 32)
n_samples = 10

X = np.random.rand(n_samples, *input_shape)
y = np.random.rand(n_samples, 1)

model = make_model(input_shape)
model.compile(loss='mse', optimizer='adam')

model.fit(X, y, epochs=10)

model.save('keras_model.h5', include_optimizer=False)
```

```bash
$ python keras_export/convert_model.py keras_model.h5 keras_model.json
```

```
Traceback (most recent call last):
  File "keras_export/convert_model.py", line 854, in <module>
    main()
  File "keras_export/convert_model.py", line 850, in main
    convert(in_path, out_path, no_tests)
  File "keras_export/convert_model.py", line 823, in convert
    json_output = model_to_fdeep_json(model, no_tests)
  File "keras_export/convert_model.py", line 808, in model_to_fdeep_json
    json_output['trainable_params'] = get_all_weights(model)
  File "keras_export/convert_model.py", line 660, in get_all_weights
    shown_layer = show_func(layer)
  File "keras_export/convert_model.py", line 357, in show_batch_normalization_layer
    assert layer_axis == -1 or layer_axis + 1 == len(layer.input_shape)
AssertionError
```

Could you please explain what's going on and what I can do to convert a model like the above?

**Comment by Dobiasd** [comment]
Hi David,

thanks for this very good report and the minimal example. I was able to easily reproduce the error locally with it.

I'll find out what is going on and come back to you with the results.

**Comment by Dobiasd** [comment]
Ah, currently, frugally-deep only supports `BatchNormalization` on the last axis of a tensor. In your example (input shape of rank 2, without batch dimension), `axis=2` (and of course `axis=-1`, the default) would work.

The assertion in `convert_model.py` simply is there to make sure only models with the supported normalization axis can be converted.

I just pushed a [commit](https://github.com/Dobiasd/frugally-deep/commit/a085aa3884e45a4709ebb7b2f43880944f2c498c), which adds a helpful error message to the assertion, such that in the future users won't have to go through all the work of trying to figure out what this `assert` means. Thanks already for helping improve the user-friendliness of fdeep.

However, this probably does not solve your problem, since, I guess, you have a good reason to normalize on the non-default axis.

I'll see if I can add the needed support for normalizing on an arbitrary axis to fdeep.

**Comment by Dobiasd** [comment]
OK, I just [added support for batch normalization on arbitrary axes](https://github.com/Dobiasd/frugally-deep/commit/61b67cc6e86889f0e920d4416bc02fa2e31d5ab5).

If you pull the latest version of frugally-deep (branch `master`), your model will work. :tada:

Thanks again for making me aware of this problem. It was really helpful, and you contributed to improving the library. :slightly_smiling_face:

**Comment by dschwertfeger** [comment]
Wow! This was blazingly fast. 🚀 

Model converts without issues now.

Thank you!
