### ISSUE TITLE
float keyword overridden?

### ISSUE THREAD

**Issue by snellejelle99** [Dobiasd/frugally-deep#201]
I have this bit of code to find the highest prediction:

    std::vector<float> results = std::vector<float>();

	    for (int i = 0; i < data.size(); i++)
	    {
		const fdeep::shared_float_vec sv(fplus::make_shared_ref<fdeep::float_vec>(data[i]));
		fdeep::tensor5 t(fdeep::shape5(1, 1, 1, 1, 52), sv);
		results.push_back(model.predict_single_output({ t }));
	    }

	    float maxvalue = std::max_element(results.begin(), results.end());

and it is giving me this error on `std::max_element` :

> Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0413	no suitable conversion function from "std::_Vector_iterator<std::_Vector_val<std::conditional_t<true, std::_Simple_types<fdeep::internal::float_type>, std::_Vec_iter_types<fdeep::internal::float_type, size_t, ptrdiff_t, fdeep::internal::float_type *, const fdeep::internal::float_type *, fdeep::internal::float_type &, const fdeep::internal::float_type &>>>>" to "float" exists	C++Game	D:\GITHUB\Royal-Game-Of-Ur-Deeplearning\PythonToC++\C++Game\NeuralNetwork.cpp	34	

After hovering over the vector definition it seems that the float keyword is overridden with `fdeep::internal::float_type` which seems to be causing this error. Is this intentional?

**Comment by Dobiasd** [comment]
It's much simpler. :slightly_smiling_face:

[`std::max_element`](https://en.cppreference.com/w/cpp/algorithm/max_element) does not return a value, but an iterator instead. It can be used like shown in the following minimal example:

```cpp
#include <algorithm>
#include <vector>

int main()
{
    std::vector<int> v{ 2, 7, 4 }; 
    std::vector<int>::iterator max_value_it;
    max_value_it = std::max_element(v.begin(), v.end());
    float max_value = *max_value_it;
}
```

Another option would be to use `fplus::maximum` (from [FunctionalPlus](https://github.com/Dobiasd/FunctionalPlus))`:

```cpp
#include <fplus/fplus.hpp>

int main()
{
    std::vector<int> v{ 2, 7, 4 }; 
    float max_value = fplus::maximum(v);
}
```

So in your case it's:

```cpp
    float maxvalue = fplus::maximum(results);
```

Since you are using frugally-deep, you already have FunctionalPlus installed.
