### ISSUE TITLE
how to extract features of an image from model

### ISSUE THREAD

**Issue by jjqcat** [Dobiasd/frugally-deep#202]
Hi, I will use frugally-deep to extract features of an image instead of predict, how to do it? Thanks

**Comment by Dobiasd** [comment]
Hi,

frugally-deep does not (need to) know anything about the semantics (business meaning) of the model (or its layers). If you have a model that does feature extraction instead of classification, using frugally-deep's `model::predict` function will return the feature tensor, i.e., `model::predict` is the generall forward-pass function in frugally-deep.

**Comment by jjqcat** [comment]
is there any way to get the result of chosen layer by name?

**Comment by Dobiasd** [comment]
No, not in frugally-deep. But before exporting your model as `.h5` in Python, you can chop off the layers after the one you are interested in, and then use that partial model in frugally-deep.
