### ISSUE TITLE
Question about predict_multi()

### ISSUE THREAD

**Issue by zhangzhishan** [Dobiasd/frugally-deep#23]
The input of function ``predict_multi()`` is ``vector<tensor3s>`` and ``tensor3s`` is ``vector<tensor3s>``.

I am a little confused about how to use ``predict_multi()``. My usage is

```
vector<float> temp;
temp.push_back(tensor3(shape3(128,1,1), internal::float_vec(inputData));
datas.push_back(temp);

model.predict_multi(datas, true);
```

I cannot understand why it is designed so.

Besides, the performance of predict multi data is so poor. Time cost using Keras is less than 1s and using ``predict_multi()`` is about 30s for the same data using the same PC.

**Comment by Dobiasd** [comment]
>  and `tensor3s` is `vector<tensor3s>`

`tensor3s` is `vector<tensor3>`

> I cannot understand why it [`predict_multi`] is designed so.

`predict` takes a `vector<tensor3>` and returns a `vector<tensor3>`, because `predict` does one single forward pass one the model. A model can take multiple tensors as input and gives multiple tensors as output. For many models the length is these vectors is simply `1`. For example a VGG net for image classification only has one input tensor, i.e. the image, and only one output tensor, i.e. the 1-hot-vector representing the classification result. But since other architectures are possible and frugally-deep wants to support them too, `predict` works with `vector<tensor3>`.

`predict_multi` simply calls `predict` several times (possibly in parallel). It does multiple forward passes on the model with different data. So it has to take a `vector<vector<tensor3>>` and also return a `vector<vector<tensor3>>`.

> Besides, the performance of predict multi data is so poor. Time cost using Keras is less than 1s and using predict_multi() is about 30s for the same data using the same PC.

Are you seeing the same effect with `predict` or just with `predict_multi`?

In case it is only with `predict_multi`, check if your memory is not exhausted by this operation. If an operating system starts to swap, everything can slow down dramatically.

In case it is also slow with `predict`, please make sure you're compiling your C++ with speed optimizations. For GCC and clang it's the `-O3` flag that you have to use. In Microsoft Visual C++ you have to use the `release` mode and not `debug`. And even if you run `release` make sure no debugger is attached to the process, i.e. start with ctrl+F5 instead of just F5.

Also remember that Keras can make use of GPU's in your PC and frugally-deep can not. So if you checked all the above and still did not solve the performance problem, run your Keras version explicitly without GPU (assuming you are using the TensorFlow backend with Cuda) like that (linux):
```bash
$ CUDA_VISIBLE_DEVICES='' python my_script.py 
```

**Comment by zhangzhishan** [comment]
I have run in release mode in Visual Studio and the time decreases to ``0.2s``. Amazing.
