### ISSUE TITLE
Invalid inputs shape while loading old TensorFlow model

### ISSUE THREAD

**Issue by ralwing** [Dobiasd/frugally-deep#254]
Hi,
I have a model created in TF 2.0 saved as json file. In current 0.15.0 version of frugally::deep i get an error:
`Invalid inputs shape.
The model takes [5(Just 1, Just 1, Just 40, Just 40, Just 1)] but provided was: [3(40, 40, 1)]`
It loaded correctly in previous version though.

After some digging i found out that the only difference is the new `rank_` field. 

I noticed that the code which creates tensors is slightly different between those versions:
in 0.15 `tensor_from_bytes` was calling 
`tensor_shape(height, width, channels)`
, however the predecessor (tensor5_from_bytes) was:
`tensor5(shape5(1, 1, height, width, channels)`
which eventually created the same input shape.

How can i fix that?

**Comment by Dobiasd** [comment]
Adjusting the existing JSON file might be tricky. The simplest way would be to re-convert the h5 file to JSON using the latest version of fdeep. If this is not possible, maybe try `fdeep::load_model` with the `verify` parameter set to `false`, since the error might be thrown by the automatic (but optional) test.
