### ISSUE TITLE
Easy re-use of input tensor

### ISSUE THREAD

**Issue by omatai** [Dobiasd/frugally-deep#255]
It may be that I am too unfamiliar with the new features of C++... but I cannot see how to re-use the memory for an input tensor over and over. That is, all tensor constructors seem to allocate new memory, then construct and return the tensor; what I want is to allocate the memory, and have the tensor constructed in that pre-allocated memory.

For example, if I have a network for classifying images that expects the common 224 x 224 x 3 image format, and I need to classify many images each second, then allocating this same memory repeatedly is something I want to avoid - I should be able to allocate the memory, and (re-)use it for each image.

Perhaps you can provide example(s) of how to convert CImg and/or OpenCV image into pre-allocated memory? If this is not possible, it is a major roadblock to using frugally deep for our application.

**Comment by Dobiasd** [comment]
Thanks for the good question. :slightly_smiling_face:

`fplus::tensor` only provides one constructor that re-uses some given memory: https://github.com/Dobiasd/frugally-deep/blob/162b5a104cab098cd8204fb7db4bad6c4efb9829/include/fdeep/tensor.hpp#L31

The other ones allocate new memory, because of specific alignment requirements for [that memory](https://github.com/Dobiasd/frugally-deep/blob/162b5a104cab098cd8204fb7db4bad6c4efb9829/include/fdeep/tensor.hpp#L167): https://github.com/Dobiasd/frugally-deep/blob/162b5a104cab098cd8204fb7db4bad6c4efb9829/include/fdeep/common.hpp#L82-L86

So if your memory is allocated like that (`Eigen::aligned_allocator`), and you provide it as an `fplus::shared_ref<std::vector<fdeep::float_type, Eigen::aligned_allocator<fdeep::float_type>>`, you *can* re-use it.

---

Another approach, which avoids repeated allocation but requires copying the values before each prediction, is to normally construct one `fdeep::tensor` of the needed shape, and then [memcopy](https://en.cppreference.com/w/cpp/string/byte/memcpy) your data into it before each prediction.

---

But in case you not already did, I highly suggest to first measure how much time each of the following three steps takes on your target platform:
- allocate memory
- copy values
- run the prediction using the actual model

In my experience, the first two things are extremely fast compared to the third one, that optimizing them does not help much for the overall performance. Here is an example:

```cpp
#include <fdeep/fdeep.hpp>

int main()
{
    fplus::stopwatch stopwatch;

    stopwatch.reset();
    const auto model = fdeep::load_model("mobilenet.json");
    const auto load_duration = stopwatch.elapsed();
    
    const std::vector<fdeep::float_type> data(224 * 224 * 3, 0.0f);

    stopwatch.reset();
    auto input = fdeep::tensor(fdeep::tensor_shape(224, 224, 3), 42.0);
    const auto allocate_duration = stopwatch.elapsed();

    stopwatch.reset();
    std::memcpy(
        &input.get_ref_ignore_rank(fdeep::tensor_pos(0)),
        data.data(),
        224 * 224 * 3 * sizeof(fdeep::float_type)
    );
    const auto memcpy_duration = stopwatch.elapsed();

    stopwatch.reset();
    const auto result = model.predict({input});
```

Output on my machine (compiled with `g++ -O3`):
```
[...]
load duration: 0.633413 s
allocate duration: 0.000071 s
memcpy duration: 0.000024 s
predict duration: 0.151699 s
```

(So we're talking about microseconds here.)

Regarding memory, yes this approach uses an extra 588 kB (224 * 224 * 3 * 4 bytes) of RAM. I don't know if this is a problem in your use-case, but keep in mind that during the prediction step, much more temporary memory might be allocated anyways.

**Comment by omatai** [comment]
Thanks - that matches my experience - roughly 1ms to set up the data, and >200ms to do the prediction. I really need to reduce that time by a factor of 10-20 ideally, so I'm going to see if ComputeCPP can help me push some of the work onto our graphics cards via OpenCL. Fingers crossed :-) If you have a better suggestion for speeding up prediction in a Windows/C++ context, I'd welcome it. So far Frugally Deep is the only possible deployment path I have been able to compile - native Tensorflow has too many porting issues; other options don't support Tensorflow 2.0+; and similar... :-(

**Comment by Dobiasd** [comment]
> roughly 1ms to set up the data, and >200ms to do the prediction

Cool. So the data-setup part does not need to be optimized, but the prediction. In one way, that's good, but

> I really need to reduce that time by a factor of 10-20 ideally

that's quite something! What performance do you get when you use raw TensorFlow?

> I'm going to see if ComputeCPP can help me push some of the work onto our graphics cards via OpenCL.

I've never tried this, but even in case it works, I'd expect this to not be faster than TensorFlow running on the GPU directly. So measuring this first might be a good way to get a "lower bound" for possible prediction runtime. If you really need low latency (and not high throughput), batching also likely would not help.

**Comment by omatai** [comment]
Yes - we need low latency; throughput is sometimes high, but mostly uneven. Tensorflow does not support GPUs other than nVidia/CUDA. In this COVID world, it is impossible for us to visit certain sites and change hardware - I am investigating options to get more out of fdeep via software alone (we have under-utilised Intel graphics cards on the systems I want to deploy on).

**Comment by Dobiasd** [comment]
Ah, understood, thanks. Sounds interesting. In case you find a way to make it faster, and want/can share, please let me know. :-)
