### ISSUE TITLE
Conv2DTranspose and Depthwise conv

### ISSUE THREAD

**Issue by ashimpd** [Dobiasd/frugally-deep#26]
Found this while searching for how to deploy keras trained models in c++. It looks very nice and useful.
Any plans for supporting Conv2DTranpose and depth-wise conv

**Comment by Dobiasd** [comment]
Thanks. Do you mean [`SeparableConv2D`](https://keras.io/layers/convolutional/#separableconv2d) when talking about "depth-wise conv"? In that case it already is [supported](https://github.com/Dobiasd/frugally-deep/blob/master/include/fdeep/import_model.hpp#L257). :)

`Conv2DTranpose` is not yet implemented because to me at one point it seemed like it is becoming unpopular due to [its problems](https://distill.pub/2016/deconv-checkerboard/). What's your use case?

**Comment by ashimpd** [comment]
Thanks for the reply. Yes SeparableConv2D is the right name.
 
I will look into the link for problems of Conv2DTranspose. My use case is kind of auto-encoder (Image to Image - Though not same image, but output size would be of same size input size)

**Comment by ashimpd** [comment]
Sorry, SeparableConv2D is not suitable. DepthwiseConv2D is different from SeparableConv2D. SeparableConv2D does depth-wise conv followed by pointwise conv. However, to implement mobilenet Batch-Norm and Relu is applied after DepthWiseConv followed by Pointwise conv. 

Mobilenet is implemented as one of the applications in keras "keras.applications.mobilenet.MobileNet"

**Comment by Dobiasd** [comment]
Ah, OK, now I know what you mean. :)

Yeah, sorry, since [DepthwiseConv2D] is not a default keras layer, but a [custom one in mobilenet](https://github.com/rcmalli/keras-mobilenet/blob/master/keras_mobilenet/depthwise_conv2d.py), it is currently not supported. I'd probably implement it if it is merged into keras core, i.e. gets [an official and fixed interface](https://keras.io/layers/convolutional/) etc.

**Comment by bobyguo** [comment]
@Dobiasd 
[DepthwiseConv2D](https://github.com/keras-team/keras/blob/master/keras/layers/convolutional.py) is already merged into keras core. Would you please implement it in fdeep? Thanks a lot.

**Comment by Dobiasd** [comment]
Thanks, did not know that. It's [still missing in the docs](https://keras.io/layers/convolutional/) but that does not matter. I'll implement `DepthwiseConv2D` and report when done.

**Comment by Dobiasd** [comment]
Mhh, it seems to not be included in TensorFlow yet:

```
$ python3 -c 'import tensorflow as tf; print(tf.__version__); from tensorflow.python.keras.layers import SeparableConv2D; from tensorflow.python.keras.layers import DepthwiseConv2D'
1.7.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'DepthwiseConv2D'
```

So I guess I'll delay writing the implementation until it's in there.

**Comment by Dobiasd** [comment]
@bobyguo: Just added [support for `DepthwiseConv2D`](https://github.com/Dobiasd/frugally-deep/commit/3d6235f4ecf01709fa3efa090d87668f69223bb5) and thus for MobileNet.

@ashimpd: Since `DepthwiseConv2D` is now available and [`UpSampling2D` seems to be a good alternative to `Conv2DTranspose`](https://distill.pub/2016/deconv-checkerboard/), I'll close this issue.

If you still need `Conv2DTranspose`, feel free to open a separate issue, since this here is mainly about `DepthwiseConv2D`.
