### ISSUE TITLE
Load model in vst3 build without absolute path

### ISSUE THREAD

**Issue by waddafunk** [Dobiasd/frugally-deep#290]
Hello and thanks for your outstanding work with this library.
I am building a VST3 plugin that makes some predictions on audio. Currently I am capable of loading the model in the build only by using absolute paths e.g. 
```
fdeep::load_model("C:\\Users\\UserName\\MyModel.json")
```
I would nonetheless like to be able to make this load procedure independent from the path of the specific machine the VST3 is running on, so that users can use the software without having to change the path in the code with their path to the model (only way i found for now to make the VST3 work on different machines) e.g. userA has to change the code with
```
fdeep::load_model("C:\\Users\\userA\\MyModel.json")
```
while for userB
```
fdeep::load_model("C:\\Users\\userB\\MyModel.json")
```  
and so on.
Is there a way to make the build load the model without having to specify the path of the current machine using the plugin?
Thanks in advance, i hope I am not asking something dumb.

**Comment by Dobiasd** [comment]
Hi,

`fdeep::load_model` takes a path to open an `std::ifstream` with. If you can express your model path as a relative path instead of an absolute one, by having the model always in the same location relative to the current working directory of your process, use that. But solving this problem looks to be unrelated to frugally-deep to me currently. :-)

In case you'd like to load your model not from a local drive (or locally mounted remote drive), but over the net, you could either copy it to local temporarily first, or use `fdeep::read_model` (for providing an arbitrary `std::istream` or `fdeep::load_model_from_string` in case you already have fetched the json content in memory.
