### ISSUE TITLE
Get float from the return value of model.predict

### ISSUE THREAD

**Issue by Jin-K-Yang** [Dobiasd/frugally-deep#291]
Hello, I wrote a simple code like this
```
const auto model = fdeep::load_model("model.json");
const auto result = model.predict({
            fdeep::tensor(fdeep::tensor_shape(static_cast<std::size_t>(5)),std::vector<float>{0, 1, 0, 1, 0})
        });
std::cout << fdeep::show_tensors(result) << std::endl;
```
and get the output like this
```
[[[[[[[0.5893]]]]]]]
```

I have two questions :
1. Why does the output has a lot of  '[' and ']'
2. How can I get the 0.5893 in this output, I just want to get the float datatype to process this result, but It seems there isn't any documentation for the API.

Thank you. This is a very convenient program, but there is no documentation to see what API I can use and how to use it. Hope you can work on this in the future~

**Comment by Dobiasd** [comment]
> Why does the output has a lot of '[' and ']'

`fdeep::model::predict` returns an instance of `fdeep::tensors`, which is a `std::vector<fdeep::tensor>`.
The reason for this is explained in ["Why does `fdeep::model::predict` take and return multiple fdeep::tensors and not just one tensor?" in the FAQ](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#why-does-fdeepmodelpredict-take-and-return-multiple-fdeeptensors-and-not-just-one-tensor).

(And each `fdeep::tensor` is multi-dimensional.)

---

> How can I get the 0.5893 in this output, I just want to get the float datatype to process this result, but It seems there isn't any documentation for the API.

Frugally-deep has a quite small API. Thus so far I did not see the need to (auto-)duplicate the few function/method definitions into an HTML page, because I guessed (but maybe I'm wrong on this) that most people nowadays use an IDE that makes it easy to explode a namespace and follow type definitions.

In your example it might look like this:

![nbMsXWv](https://i.imgur.com/nbMsXWv.png)
![dB1Qhj9](https://i.imgur.com/dB1Qhj9.png)
![95j4Xq8](https://i.imgur.com/95j4Xq8.png)

So just from looking at the types, the following would do the trick:

```cpp
result.front().as_vector()->front()
```

But there is a helper function available for you. It's `fdeep::model::predict_single_output`. You can find it like this:

![h4IO46o](https://i.imgur.com/h4IO46o.png)

If you then jump to the definition, you'll see the following [explanation](https://github.com/Dobiasd/frugally-deep/blob/8ef3e60edeee3a0af4d6e12d6c89255b0ef203ec/include/fdeep/model.hpp#L94-L98):

```cpp
// Convenience wrapper around predict for models with
// single tensor outputs of shape (1, 1, 1),
// typically used for regression or binary classification.
// Returns this one activation value.
```

So you can do the following:

```cpp
const auto result = model.predict_single_output(...
```

`result` will then be a simple `float`.

---

> there is no documentation to see what API I can use and how to use it. Hope you can work on this in the future

If you can give a concrete explanation of what kind of docs you'd like to see, please let me know. Of course, I'm also happy about a pull request. :slightly_smiling_face:

**Comment by Jin-K-Yang** [comment]
Thank you very much, It seems my VS code's function of list members went something wrong.
