### ISSUE TITLE
support for tensorflow1.x keras2

### ISSUE THREAD

**Issue by chocolate-byte** [Dobiasd/frugally-deep#294]
as far as i know , keras with tensorflow2.X is 5 times slower than simply using tensorflow1 with keras, it's due to the tf.keras and keras difference, any help of supporting tf1 would be appreciate!

**Comment by Dobiasd** [comment]
Where do you have this information from? Don't you think there would have been a huge outrage in the community if the performance drops by a factor of 5? :wink: Many people would not switch to the new version because of this.

So, no, in my experience, there is no such huge performance difference. 

To base this on actual numbers, I just created two `Dockerfile`s to compare the performance of Keras + TensorFlow 1.x with the performance of TensorFlow 2.x:
- keras `2.2.5` + tensorflow `1.15.5`: https://gist.github.com/Dobiasd/e2bbb6709816436ac6ac7b3820381067
- tensorflow `2.5.0`: https://gist.github.com/Dobiasd/29c74c234c12c38e380f0970d4545c59

Results (average runtime of 20 predictions on a VGG19 model, measured on an Intel Core i5-6600 CPU @ 3.30GHz):
- keras `2.2.5` + tensorflow `1.15.5`: 0.1747462427476421 s
- tensorflow `2.5.0`: 0.20418983689742162 s

So there is a difference, but, at least in this example, it's not that large. I currently don't see frugally-deep supporting TensorFlow 1.x (again) in the future.

**Comment by chocolate-byte** [comment]
actually i've tried tf.keras before, and i got the result of time increased enormous  in tf2,
here's the same issue and i guess the reason is because of eager
https://github.com/tensorflow/tensorflow/issues/33487

**Comment by Dobiasd** [comment]
Ok, thanks, I see. It seems the difference measured there is about training, not about prediction.

Is it possible to train and save a model with TF 1.x, and then load it with Tf 2.x (if needed with some conversion beforehand)? If yes, nothing stops you from using TF-1.x models with frugally-deep. :slightly_smiling_face:

**Comment by Dobiasd** [comment]
For reference: I just tested saving a model as `h5` with keras 2.2.5 and tensorflow 1.15.5, and then loading it again with tensorflow 2.5.0. At least for the example model used (VGG19), it works fine (see [this `Dockerfile`](https://gist.github.com/Dobiasd/e858fd1fbb157e42c193fb4067dafc30)). :tada:

So in case any future reader wants to use their TF 1.x model with frugally-deep, this should be the first option to try. :slightly_smiling_face:
