### ISSUE TITLE
Using fdeep with video

### ISSUE THREAD

**Issue by besmaGuesmi** [Dobiasd/frugally-deep#305]
Hi!

Is there any way to use deep with video, I tried to divide the videos into frames and then use each frame as Mat, but the method is slow. Any help! thanks

**Comment by Dobiasd** [comment]
Hi,

if you're diving your video into frames or process it otherwise, is not a property of frugally-deep, but of your model. So I guess in TensorFlow you're doing the same.

In case you've not yet read the first 4 questions and answers in the FAQ (they are performance-related), I recommend doing that: https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md

**Comment by besmaGuesmi** [comment]
Thank you I'll check it.
