### ISSUE TITLE
hi thanks for your greate work ,  where is the conv1d layer class and could support network quantification?

### ISSUE THREAD

**Issue by Hongpeng1992** [Dobiasd/frugally-deep#320]
- Before reporting an issue, please make sure you are using the latest versions of frugally-deep, and [the right TensorFlow version](README.md#requirements-and-installation).

- Also check out the [FAQ](../FAQ.md). Maybe your problem/question is common and there already is a canonical answer for it.

- If you have a model and you get unexpected errors when converting it for or when using it with frugally-deep, please upload and post a link to your model file (`.h5`).

- Please try to make the problem reproducible by providing a [SSCCE](http://sscce.org/) as code.

- Feel free to also submit any other feedback, suggestions or questions you might have. :)

**Comment by Dobiasd** [comment]
> hi thanks for your greate work

Hi, and thanks. :slightly_smiling_face:

> where is the conv1d layer class [...]?

There is [no explicit `conv_1d_layer` class](https://github.com/Dobiasd/frugally-deep/tree/fda22ee4fb22f8004a4acb6564cc74c142369e88/include/fdeep/layers), because in the implementation of frugally-deep, the [`Conv1D` layer](https://keras.io/api/layers/convolution_layers/convolution1d/) is just a special case of the [`Conv2D` layer](https://keras.io/api/layers/convolution_layers/convolution2d/). So [it's mapped accordingly when loading a model](https://github.com/Dobiasd/frugally-deep/blob/fda22ee4fb22f8004a4acb6564cc74c142369e88/include/fdeep/import_model.hpp#L1164). But when simply using the library, that's an implementation detail you normally don't need to care about. :relaxed:

> and could support network quantification?

Could you please elaborate what you mean exactly?

**Comment by Hongpeng1992** [comment]
> > hi thanks for your greate work
> 
> Hi, and thanks. slightly_smiling_face
> 
> > where is the conv1d layer class [...]?
> 
> There is [no explicit `conv_1d_layer` class](https://github.com/Dobiasd/frugally-deep/tree/fda22ee4fb22f8004a4acb6564cc74c142369e88/include/fdeep/layers), because in the implementation of frugally-deep, the [`Conv1D` layer](https://keras.io/api/layers/convolution_layers/convolution1d/) is just a special case of the [`Conv2D` layer](https://keras.io/api/layers/convolution_layers/convolution2d/). So [it's mapped accordingly when loading a model](https://github.com/Dobiasd/frugally-deep/blob/fda22ee4fb22f8004a4acb6564cc74c142369e88/include/fdeep/import_model.hpp#L1164). But when simply using the library, that's an implementation detail you normally don't need to care about. relaxed
> 
> > and could support network quantification?
> 
> Could you please elaborate what you mean exactly?

Thanks for your reply,  like int8 quantization?

**Comment by Dobiasd** [comment]
Ah, ok, thanks.

No, currently this is not yet supported, and so far there are plans for implementing this in frugally-deep.

**Comment by dav-ell** [comment]
Interested in seeing quantized model support in this repo, as it would let folks use it with larger models on microcontrollers like RPi Pico and ESP32s. Without quantization, models on ESP32 are often limited to <20k params.
