### ISSUE TITLE
How to convert result to opencv image

### ISSUE THREAD

**Issue by XiujianLiu** [Dobiasd/frugally-deep#326]
Thank you so much for the last answer. I have another question: how to convert the output ' result' from

const auto result = model.predict({ input });

to opencv image? Is there a code sample? I'm using u-net for segmentation, the result supose to be a mask image.

**Comment by Dobiasd** [comment]
See ["How to convert an `fdeep::tensor` to an (OpenCV) image and back?" in the FAQ](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#how-to-convert-an-fdeeptensor-to-an-opencv-image-and-back).

**Comment by XiujianLiu** [comment]
so result is a fdeep::tensor? Here is what i did:

cv::Mat convertToMat(const fdeep::tensors &tensor)
{
	const cv::Mat image2(
		cv::Size(tensor.at(0).shape().width_, tensor.at(0).shape().height_), CV_32FC1);
	fdeep::tensor_into_bytes(tensor.at(0),
		image2.data, image2.rows * image2.cols * image2.channels());

	return image2;
}
int main()
{
	const auto result = model.predict({ input });

	std::cout << fdeep::show_tensors(result) << std::endl;

	cv::Mat rm = convertToMat(result);
	cv::Mat rm_8;
	rm.convertTo(rm_8, CV_8UC1, 255);
}

it's correctly output a image mask.

 but if i wouldn't call this function 
         std::cout << fdeep::show_tensors(result) << std::endl;
it will always be a black image.

**Comment by XiujianLiu** [comment]
Ok, you can download my project in this link:

https://share.weiyun.com/i45MPEXc

Results are different from time to time.
 somtime it shows correct answer, sometime doesn't, you can try the same input image many times.

thanks!

**Comment by Dobiasd** [comment]
Sorry, but I don't know how to download anything from [that page](https://i.imgur.com/Rl5on2q.png), because I don't know the language. I've tried randomly clicking stuff, but to no avail.

Also, it would be great if you could create a minimal example of your problem for me to reproduce it without needing to dig through your whole project.

In general, if I understand correctly, you're hypothesizing, that `fdeep::show_tensors` does change the content of the argument passed to it, even though the parameter is a `const` reference. That's a quite bold hypothesis, and I feel you should provide a minimal example to reproduce and prove it. ;)

**Comment by XiujianLiu** [comment]
it's a minimal example, because i include the .json file which makes the .rar file so big.
i have no luck upload the .zip file in here, so i using the external driver.
Follow two steps you can download that file i think. 
![微信截图_20220307190529](https://user-images.githubusercontent.com/89759319/157019925-10bf65bc-07cb-4c86-9558-1eb92defe917.png)

Thank you for your time, sir.

**Comment by XiujianLiu** [comment]
Yes, sir. I uploaded the minimal example to Google Drive, Hope you can download it. 
The coding IDE is vs 2015, 
https://drive.google.com/file/d/1qexiQ56gCfmigvRRWxoPIpW9aNVFbo9o/view?usp=sharing

**Comment by Dobiasd** [comment]
Ok, I was able to download it. You could have left out all the non-relevant stuff, especially the output files from your IDE/compiler, but, well, I found the file of interest, i.e., `aiTest.cpp`.

However, when I try to compile it using `g++ -std=c++14 -O3 aiTest.cpp -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -lopencv_highgui -o aiTest`, I get stuff like this:

```
[...]
aiTest.cpp:129:25: warning: null character(s) ignored
aiTest.cpp:129:26: warning: null character(s) preserved in literal
aiTest.cpp:129:37: warning: null character(s) ignored
[...]
aiTest.cpp:1:3: error: expected unqualified-id before ‘/’ token
    1 | ��/ /   a i T e s t . c p p   :   a n   a s c i t e s   d e t e c t i o n   A I   p r o j e c t   
      |   ^
aiTest.cpp:35:2: error: ‘i’ does not name a type
   35 |    s t d : : c o u t   < <   f d e e p : : s h o w _ t e n s o r s ( r e s u l t )   < <   s t d : : e n d l ;   
      |  ^
```

(full output: https://gist.github.com/Dobiasd/99555707ecfe548b6aaa93fe368d0c8b)

So it seems there is something off with the file encoding. Thus I tried to remove the null characters from the file using `tr < aiTest.cpp -d '\000' > aiTest2.cpp`, but then the content no longer looks like source code, but like this: https://gist.githubusercontent.com/Dobiasd/0bce59710c66e6491e4c927e091faba9/raw/cc5b5c364866de81740c7f009c0a8fa5e773af9f/gistfile1.txt

Sorry, but this is going nowhere. Please provide an actual minimal example that automatically reproduces your observation (for the sake of cross-machine compatibility) as a `Dockerfile` (example here: https://gist.github.com/Dobiasd/82a6d2149ca7dd765af0686b45e5df55).

Otherwise, I can't help you. Also, I don't have the time to provide time-intense consulting (or programming-beginner training) for free.

**Comment by XiujianLiu** [comment]
As i dug into the source I figured it out that i was using fdeep::tensor_from_bytes incorectly.
here is right code in a medical image segmentation project using U-net, which outputs great answer.
By the way, Thanks Dobiasd for all your replies!

#include <fdeep\fdeep.hpp>
#include <opencv2/opencv.hpp>

cv::Mat convertToMat(const fdeep::tensors &tensor)
{
	const cv::Mat image2(
		cv::Size(tensor.at(0).shape().width_, tensor.at(0).shape().height_), CV_32FC1);
	const auto values = tensor.at(0).to_vector();
	std::memcpy(image2.data, values.data(), values.size() * sizeof(float));

	return image2;
}

int main()
{
	const cv::Mat img = cv::imread("./test/origin/7 (7).jpg");
	cv::Mat image;
	// convert image to grayscale and the dimension (128 X 128) as U-net input layer required
	cv::cvtColor(img, image, cv::COLOR_BGR2GRAY);
	cv::resize(image, image, cv::Size(128,128), 0, 0, cv::INTER_NEAREST);

	assert(image.isContinuous());
	const auto model = fdeep::load_model("fdeep_model.json");
	const auto input = fdeep::tensor_from_bytes(image.ptr(),
		static_cast<std::size_t>(image.rows),
		static_cast<std::size_t>(image.cols),
		static_cast<std::size_t>(image.channels()),
		0.0f, 255.0f);
	const auto result = model.predict({ input });

	cv::Mat result_mat = convertToMat(result);
	//cv::Mat result_mat_8;
	//// convert float point 0.0f~1.0f to uint8 0~255
	//result_mat.convertTo(result_mat_8, CV_8UC1, 255);
	//cv::Mat mask_show;
	//// resize as input image size
	//cv::resize(result_mat_8, mask_show, cv::Size(img.cols, img.rows));
	//cv::imshow("mask", mask_show);

	cv::Mat mask;
	cv::resize(result_mat, mask, cv::Size(img.cols, img.rows));
	// fuse the mask to the input image and show
	for (int y = 0; y < img.rows; y++)
	{
		cv::Vec3b *ptr_y = (cv::Vec3b*)(img.ptr<cv::Vec3b>(y));
		float *ptr_src = mask.ptr<float>(y);
		for (int x = 0; x < img.cols; x++)
		{
			if (ptr_src[x] > 0.8)
			{
				// alpha fusion
				ptr_y[x][0] = ptr_y[x][0]*0.8+0.2*255;
				ptr_y[x][1] = ptr_y[x][1] * 0.8 + 0.2 * 0;
				ptr_y[x][2] = ptr_y[x][2] * 0.8 + 0.2 * 255;
			}
			
		}
	}
	cv::imshow("cook", img);
	cv::waitKey();
    return 0;
}
