### ISSUE TITLE
Can't print vector shape in sum_tensors()

### ISSUE THREAD

**Issue by SwatikSahoo** [Dobiasd/frugally-deep#334]
Hi Tobias,

I am facing some issues with the sum_tensor(). Kindly see the below code and the issues with it.

`inline tensor sum_tensors(const tensors& ts)
{
static int s_ = 0;
s_+=1;
assertion(!ts.empty(), "no tensors given");
assertion(
fplus::all_the_same_on(fplus_c_mem_fn_t(tensor, shape, tensor_shape), ts),
"all tensors must have the same size");
const auto ts_values = fplus::transform(
fplus_c_mem_fn_t(tensor, as_vector, shared_float_vec), ts);
float_vec result_values;
result_values.reserve(ts_values.front()->size());
if(s_==1){
std::cout << fplus::show_cont(ts_values)<< "\n" << std::endl;
std::cout << fplus::show(ts_values)<< "\n" << std::endl;
std::cout << ts_values.front()->size()<< "\n" << std::endl;

}
for (std::size_t i = 0; i < ts_values.front()->size(); ++i)
{
    float_type sum_val = static_cast<float_type>(0);
    for (const auto& t_vals : ts_values)
    {
        sum_val += (*t_vals)[i];
    }
    result_values.push_back(sum_val);
}
return tensor(ts.front().shape(), std::move(result_values));
}`

**Issues-**

1- Why doesn't it print the show_cont(ts_values)?
2- Is there any fplus function that I can use to copy the elements traversed by (*t_vals)[i] to a vector and I also want to see the shape of ts_values?

**Comment by SwatikSahoo** [comment]
Here I am trying to predict the class of a single image. So is it possible that the sum_tensor is not called even once in this case?

**Comment by Dobiasd** [comment]
> Why doesn't it print the show_cont(ts_values)?

Maybe you don't call `sum_tensors` in your main program (which you don't show here). Maybe `s_==1` is not `true`. I mean, you have `static int s_ = 0;` and then `s_+=1;` So `s_==1` will only be `true` for the first invocation of the function since the value in the `static` variable "survives" going out of scope.

> Is there any fplus function that I can use to copy the elements traversed by (*t_vals)[i] to a vector and I also want to see the shape of ts_values?

For tensor-to-vector conversion, see ["How to convert an `fdeep::tensor` to an `std::vector<float>`?" in the FAQ](https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md#how-to-convert-an-fdeeptensor-to-an-stdvectorfloat.

`ts_values` in that case, does not have a tensor-like shape, because it's an `std::vector<std::vector<float>>`. If you have an actual tensor, you can get the shape of it by using the `fdeep::tensor::shape` member function.

> So is it possible that the sum_tensor is not called even once in this case?

I don't know. For that, you would need to create a [minimal example](http://sscce.org/), such that I can see what you're actually doing.

---

In general, I don't know you think you need to copy-paste the `sum_tensors` function out of the library and modify it. :shrug:

**Comment by SwatikSahoo** [comment]
This is the code where I am trying to predict the class of hen.jpg

`#include <fdeep/fdeep.hpp>
#include <opencv2/opencv.hpp>
#include "ImageNetLabels.hpp"

int main()
{
    int a;
    cv::Mat image = cv::imread("hen.jpg");
    cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
    assert(image.isContinuous());
    cv::resize(image, image, cv::Size(224, 224), 0, 0, cv::INTER_CUBIC);
    const auto model = fdeep::load_model("mobilenet.json");
    // Use the correct scaling, i.e., low and high.
    const auto input = fdeep::tensor_from_bytes(image.ptr(),
        static_cast<std::size_t>(image.rows),
        static_cast<std::size_t>(image.cols),
        static_cast<std::size_t>(image.channels()),
        0.0f, 1.0f);
    fplus::stopwatch stopwatch;
    const auto result = model.predict_class({input});
    std::cout << "lapse - " + fplus::show_float(0, 6, stopwatch.elapsed()) + "\n" << std::endl;
    ImageNetLabels obj; 
    std::cout << "result - " + result <<"\n" << std::endl;
    std::cout << obj.imagenet_labelstring( result ) << std::endl;; 
}`

And I have used gcc profiler on its executable file. Here in the screenshot, you can see the number of times it's called and the time taken by it.
![Screenshot (129)](https://user-images.githubusercontent.com/72124736/158322652-b36bac18-0196-4cf4-b272-79a1ff2984c5.png)

I still don't understand why sum_tensor is not called in predicting a single image?

**Comment by Dobiasd** [comment]
Maybe you've modified the wrong copy of `tensor.hpp`, or maybe you did not re-compile to the target you're using. I can't know.

If you set a breakpoint in the function, or just print out something at the beginning of the function (without any `if` around it), you should be able to find out.

**Comment by SwatikSahoo** [comment]
> 



> Is there any fplus function that I can use to copy the elements traversed by (*t_vals)[i] to a vector and I also want to see the shape of ts_values?

Here, how can I copy the set of elements to a vector whose sum is being calculated in each iterations of the outer for loop?

**Comment by Dobiasd** [comment]
Sorry, I think I don't fully get the question. But to me, your problem seems to not be related to frugally-deep. It looks more like a general problem with functions, loops, and vectors. Working on this context here is outside of the scope. I suggest you reduce your problem to a minimal example (not involving frugally-deep at all anymore) and then try to solve it, optionally with asking on StackOverflow or similar.
