### ISSUE TITLE
Global variable for model instance

### ISSUE THREAD

**Issue by nikolay-olkhovskiy** [Dobiasd/frugally-deep#342]
When trying to create a global variable and later load a model into it in a function the error occurs "No appropriate default constructor for fdeep::model". What is a right way to create a global variable for fdeep::model and use it in different functions?
```c++
#include <fdeep/fdeep.hpp>
using namespace std;

fdeep::model DNN;

void model_init() {
DNN = fdeep::load_model("fdeep_model.json");
}

void model_run() {
DNN.predict(...);
}

int main(){

model_init();
model_run();

return 0;
}
```

**Comment by Dobiasd** [comment]
Not having a default constructor for `fdeep::model` is a feature. :wink: It's there to help users to avoid problematic conditions, e.g.:

```cpp
// The following code does not compile on purpose.
fdeep::model model;

// ...

model = load_model("model.json");
```

If you now would use `model.predict` or such after constructing but before loading, it could only create an error, like triggering an assertion, raising an exception, returning an empty vector or tensors, etc. Since a model in that state does not make sense, it is prevented from existing in the first place.


Instead of having the model global like this:

```cpp
#include <fdeep/fdeep.hpp>

fdeep::model DNN; // Does not compile.

void model_init() {
    DNN = fdeep::load_model(...);
}

void model_run() {
    DNN.predict(...);
}

int main() {
    model_init();
    model_run();
}
```

I'd usually just pass it around as a function parameter:

```cpp
#include <fdeep/fdeep.hpp>

fdeep::model model_init() {
    return fdeep::load_model(...);
}

void model_run(const fdeep::model& dnn) {
    dnn.predict(...);
}

int main() {
    const auto dnn = model_init();
    model_run(dnn);
}
```

But if you really want it to be global (with all the usual downsides of global variables), you can express the possibility of not having a model at all before initializing it by using something like `std::optional<fdeep::model>`:

```cpp
#include <fdeep/fdeep.hpp>

#include <optional>

std::optional<fdeep::model> DNN;

void model_init() {
    DNN = fdeep::load_model(...);
}

void model_run() {
    DNN.predict(...);
}

int main() {
    model_init();
    model_run();
}
```
