### ISSUE TITLE
Is there a support for Rescaling layer?

### ISSUE THREAD

**Issue by TrueWodzu** [Dobiasd/frugally-deep#344]
Hi Tobias,

just as today, I've converted EfficientNetB3 model from Keras Applications. This model contains Rescaling layer as a way to preprocess data. Conversion went fine and I am just wondering, did you add support for Rescaling layer? [Last time](https://github.com/Dobiasd/frugally-deep/issues/272) when I did some conversion, I had to simulate Rescaling, but now, the conversion script has not returned me any errors. So am I all good? (Rescaling layer is not mentioned on the readme page as being supported).

**Comment by Dobiasd** [comment]
Hi.

I did not implement support for the [`Rescaling` layer](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Rescaling) in frugally-deep. But since it's no longer experimental in Keras, I will think about adding it. :slightly_smiling_face: Thanks for reminding me. :+1:

The reason why your conversion succeeded is, that [`EfficientNetB3` in Keras (`2.8.0`) Applications](https://github.com/keras-team/keras/blob/v2.8.0/keras/applications/efficientnet.py#L321) does not use a `Rescaling` layer. :white_check_mark:

**Comment by TrueWodzu** [comment]
Hi,

Thanks for answering, but I don't understand. You've pointed me to the source and even to the exact line:

`x = layers.Rescaling(1. / 255.)(x)`
which basically adds Rescaling layer to the model?:confused:

And when I print model summary, I will get:

```
Model: "efficientnetb3"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_1 (InputLayer)           [(None, 300, 300, 3  0           [])]
 rescaling (Rescaling)          (None, 300, 300, 3)  0           ['input_1[0][0]']
 normalization (Normalization)  (None, 300, 300, 3)  7           ['rescaling[0][0]']
```

Could you please explain? :pray:

**Comment by Dobiasd** [comment]
Ah, sorry. My mistake. :woozy_face:

I thought, only the ["normal" EfficientNet](https://github.com/keras-team/keras/blob/v2.8.0/keras/applications/efficientnet.py#L207) would use `Rescaling`, and [EfficientNetB3](https://github.com/keras-team/keras/blob/v2.8.0/keras/applications/efficientnet.py#L606) would not. But it turns out [EfficientNetB3 *is* an EfficientNet instance](https://github.com/keras-team/keras/blob/v2.8.0/keras/applications/efficientnet.py#L614), so (as your model summary confirms), it is using `Rescaling` too. I'll debug what's going on and get back to you.

Interesting! :detective:

**Comment by TrueWodzu** [comment]
I confirm the exception. I thought that if something is not supported it will be reported during the conversion of the model with Python script.

How long do you think it will take you to add this layer? Is it a matter of weeks or longer?:)

**Comment by Dobiasd** [comment]
An outage of jcenter.bintray.com is kinda blocking me at work, so I found some time for `Rescaling` already. Once the CI of the PR is green, I'll merge it into master and tag a new version.

**Comment by Dobiasd** [comment]
Done. :heavy_check_mark: (see [version `0.15.17`](https://github.com/Dobiasd/frugally-deep/releases/tag/v0.15.17-p0) :slightly_smiling_face:)

**Comment by TrueWodzu** [comment]
Splendid! :clap: Thank you. :pray: :smile:
