### ISSUE TITLE
how to convert such model with convert_model.py?

### ISSUE THREAD

**Issue by 4SmarterWorld** [Dobiasd/frugally-deep#37]
Hi, when i use this convert_model.py to convert fer2013_mini_XCEPTION.102-0.66.hdf5 from
https://github.com/oarriaga/face_classification,
i encountered with such problems:
UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '
2018-04-09 18:42:36.375958: F tensorflow/core/kernels/mkl_input_conversion_op.cc:448] Check failed: tf_input.CheckReorderToOpMem( memory::primitive_desc(output_mkl_md, cpu_engine), tensor_out, &net) == true (0 vs. 1)

i don't know what is wrong, can you help me out?

**Comment by Dobiasd** [comment]
Since you only convert for prediction, the optimizer is not relevant. Are these just warnings and you can continue or are these errors blocking further executing?

In case they don't block, I guess you can simply ignore them.

**Comment by Dobiasd** [comment]
I downloaded the repo and converted two of the models there with success:

```bash
python3 convert_model.py face_classification/trained_models/fer2013_big_XCEPTION.54-0.66.hdf5 fer2013_big_XCEPTION.54-0.66.json
```

```bash
python3 convert_model.py face_classification/trained_models/emotion_models/simple_CNN.985-0.66.hdf5 simple_CNN.985-0.66.json
```


Also loading the result of the conversion using frugally-deep also worked:

```cpp
fdeep::load_model("fer2013_big_XCEPTION.54-0.66.json", true);
```

```cpp
fdeep::load_model("simple_CNN.985-0.66.json", true);
```

During the conversion step I also received this message
```
/usr/local/lib/python3.5/dist-packages/keras/models.py:291: UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '
```
however since it is just a warning and not an error, everything continued normally. As explained earlier I think this warning can be ignored.

Please make sure you are using the latest versions of TensorFlow, Keras and frugally-deep. And then try to convert again. If you still encounter problems, please re-open this issue and post the steps you use to reproduce the problem.
