### ISSUE TITLE
`visualize_layers.py` uses `scipy.misc.imsave` which no longer exists

### ISSUE THREAD

**Issue by torokati44** [Dobiasd/frugally-deep#371]
The documentation suggests switching to `imageio.imwrite` instead: https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.imsave.html

There's even a migration guide: https://imageio.readthedocs.io/en/v2.6.1/scipy.html

Another alternative would be `keras.preprocessing.image.save_img`.

**Comment by Dobiasd** [comment]
Thanks a lot. :+1: I just [replaced](https://github.com/Dobiasd/frugally-deep/commit/0c20d5946b473aa350f0260458c4822cc1cb193f) `scipy.misc.imsave` with `imageio.imwrite`.

However, the script itself is quite outdated, i.e., it does not work anymore with current TensorFlow versions.

I'm considering removing it completely, since, honestly, I think it does not have much to do with the actual purpose of frugally-deep, and was more like an experiment I did in the past. What do you think?

**Comment by torokati44** [comment]
Thanks a lot for the quick response!
I'm not really attached to this script - as I have not been able to run it successfully.
I think https://netron.app/ serves its (suspected) purpose instead of it quite well.

**Comment by Dobiasd** [comment]
netron.app visualizes the model architecture.

`frugally-deep/keras_export/visualize_layers.py` did something different, i.e., the stuff from this article: 
https://blog.keras.io/how-convolutional-neural-networks-see-the-world.html

**Comment by torokati44** [comment]
Oooh, I see. Then I guessed wrong. This looks really cool! :thinking:
Anyway, the model I'm currently working with has no convolutional layers, so I personally won't miss it.
Given the link above (and the git history of this repo), something like this could be put together again fairly easily in the future if someone ends up needing it...?

**Comment by Dobiasd** [comment]
Yeah, I guess so. Anyway, it probably should not be part of the frugally-deep repo, since it has nothing to do with running Keras models in C++. :grin:
