### ISSUE TITLE
/usr/bin/ld: cannot find -lnlohmann_json

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/frugally-deep#38]
Current [travis builds fail](https://api.travis-ci.org/v3/job/365106440/log.txt) with the following error:

```
[ 15%] Built target readme_example_main_data
Scanning dependencies of target readme_example_main
[ 23%] Building CXX object test/CMakeFiles/readme_example_main.dir/readme_example_main.cpp.o
[ 30%] Linking CXX executable readme_example_main
/usr/bin/ld: cannot find -lnlohmann_json
```
Any ideas on what could cause this?
/cc @headupinclouds

**Comment by headupinclouds** [comment]
It looks like the installation target names changed in this commit (yesterday):
https://github.com/nlohmann/json/commit/b8bfd1140d272358f02c61b2f5319a5509a1ed74

By default, `frugally-deep/.travis.yml` is installing dependencies from `HEAD` of the default branches, so there is no guarantee something fundamental won't change in the installation:

Where we have:

```
  - git clone https://github.com/nlohmann/json
  - cd json
  - mkdir -p build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
```

it is probably better to use tagged releases in the CI files, like this:

```
  - git clone https://github.com/nlohmann/json
  - cd json
  - git checkout v3.1.2 ### checkout a specific tested version
  - mkdir -p build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
```

If you add `git checkout v3.1.2` I believe all will be well again with the current build files.  Similar changes could be made for these:

```
  - git clone https://github.com/onqtam/doctest
  - git clone https://github.com/Dobiasd/FunctionalPlus
  - git clone https://github.com/eigenteam/eigen-git-mirror
```

Building with `HUNTER_ENABLED=ON` will effectively do the same thing (use stable versions) and it should work fine.

That last `json` commit added an installation namespace, so in the next release you would use:

```
target_link_libraries(fdeep INTERFACE nlohmann_json::nlohmann_json)
```

instead of:

```
target_link_libraries(fdeep INTERFACE nlohmann_json)
```

This hasn't been included in a release yet:

https://github.com/nlohmann/json/releases

The author usually sends the updates to Hunter shortly after each release.

**Comment by Dobiasd** [comment]
You are awesome!

Thank you very much (as usual). The explanation is very clear and your suggested fix of course [works](https://travis-ci.org/Dobiasd/frugally-deep/builds/365189894?utm_source=email&utm_medium=notification).

**Comment by headupinclouds** [comment]
Glad I could help!
