### ISSUE TITLE
Conan packages of this library are often outdated

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/frugally-deep#400]
Conan (as opposed to Conda) does not automatically fetch the latest version.

Pushing the latest version to Conan is a manual process (forking their repo, adjusting the files, creating a PR, and waiting, see [example](https://github.com/conan-io/conan-center-index/pull/19933)). I find it quite annoying.

So maybe it's time to drop support for Conan, i.e., remove it from the installation instructions, no longer publish new versions there, and open a removal PR in their repo.

**Comment by Dobiasd** [comment]
Hi, and thanks a lot for taking the time to give such a nice and kind explanation of the state of affairs! :heart:

And you are right. Conan's extensive verification process *did* reveal a problem in frugally-deep. :rocket:

The dashboard, you linked to, with the one-click-pull-request feature looks like an absolute game-changer for me! :heart_eyes: Knowing about this, I'll happily give it a try on my next release of FunctionalPlus or frugally-deep. :+1:

**Comment by ericLemanissier** [comment]
FYI, you can also update a recipe's dependencies with another tool : https://ericlemanissier.github.io/conan-center-index-bump-deps/ (it uses https://github.com/conan-io/conan-extensions/tree/main/extensions/commands/recipe under the hood)

**Comment by Dobiasd** [comment]
@qchateau I just tried to add the new version of frugally-deep to Conan using https://qchateau.github.io/conan-center-bot/#/updatable

but creating the PR [fails](https://i.imgur.com/OFjshSL.png) with `Pull request creation failed. Validation failed: must be a collaborator`.

Could you help me with that?

**Comment by Dobiasd** [comment]
@ericLemanissier I also looked into your tool https://ericlemanissier.github.io/conan-center-index-bump-deps/
but frugally-deep is not listed there. Do I first need to register it somewhere?

**Comment by ericLemanissier** [comment]
Because as far as I can see, all the dependencies of frugally-deep are already bumped to the latest version

**Comment by Dobiasd** [comment]
@ericLemanissier :bulb: Ah, sorry, I had misunderstood the purpose of your tool. :grimacing: I thought it's an alternative to the one by qchateau. But now I understand, what it's actually for. Thanks a lot, things make sense to me now. :+1:

Now, I hope there's a way to make qchateau's tool work for me.. :slightly_smiling_face:

**Comment by ericLemanissier** [comment]
Yeah, the problem is tracked in https://github.com/qchateau/conan-center-bot/issues/111

The nice thing with conan-center-bot is that you can fork qchateau's repo, and enable its github actions, and you will get your own web pages to do the bumps, which won't have the privileges problem because you will be the owner.
Alternatively, conan-center-bot is a command-line tool which you can install and run manually

**Comment by Dobiasd** [comment]
Oh, thanks for the explanation and alternative! :heart:

For now, I used the old way of creating [the PR](https://github.com/conan-io/conan-center-index/pull/20740) manually. :white_check_mark:

**Comment by Dobiasd** [comment]
@ericLemanissier Hi, I've successfully used
https://qchateau.github.io/conan-center-bot/#/updatable
a few times, but today I'm running into a new problem:
`[HOOK - conan-center.py] pre_export(): '_HooksOutputErrorCollector' object has no attribute 'warning'`
Could you help me once more?
![5WkooE5](https://i.imgur.com/5WkooE5.png)
🙏

**Comment by ericLemanissier** [comment]
This happens because there is an error on this line : https://github.com/conan-io/hooks/blob/b92e54f4524166ed4ef1f9727034ddd8e1a4eaef/hooks/conan-center.py#L201 . it should be `output.warn`.

But as you can see in the warning message, and the full log https://github.com/qchateau/conan-center-bot/actions/runs/12862129028/job/35856576726#step:10:8706 conan-center-bot has been rotting for several month, because it still uses conan 1 and conan-center-hook. I guess nobody is using this tool any more

**Comment by Dobiasd** [comment]
Ah, ok, thanks!

Is there a new tool that solves the problem, or do we have to create our pull requests manually again?

**Comment by ericLemanissier** [comment]
AFAIK, you have to create PRs by hand

**Comment by Dobiasd** [comment]
Oh, ok. So I've created [the pull request](https://github.com/conan-io/conan-center-index/pull/26423) manually. Thanks! 👍
