### ISSUE TITLE
Problem on loading h5 model

### ISSUE THREAD

**Issue by anguoyang** [Dobiasd/frugally-deep#41]
Hi, can anyone help me on this problem? thank you.

-----------------------------------------
E:\DeepLearning\keras\frugally-deep>python keras_export/convert_model.py mask_rcnn_coco.h5 fdeep_model.json
C:\Program Files\Python35\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
loading mask_rcnn_coco.h5
Traceback (most recent call last):
  File "keras_export/convert_model.py", line 504, in <module>
    main()
  File "keras_export/convert_model.py", line 500, in main
    convert(in_path, out_path)
  File "keras_export/convert_model.py", line 447, in convert
    model = load_model(in_path, custom_objects={'relu6': relu6})
  File "C:\Program Files\Python35\lib\site-packages\keras\models.py", line 268, in load_model
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.

**Comment by Dobiasd** [comment]
Please make sure the path to `mask_rcnn_coco.h5` is correct. Your current call to `convert_model`, expects is to be in the current working directory, i.e. `E:\DeepLearning\keras\frugally-deep` in your case.

Also please check if you can load your model normally with Keras:
```python
from keras.models import load_model
model = load_model('mask_rcnn_coco.h5')
```

If this does not help, please re-open this issue, upload the model and post the link, so I can reproduce the problem.

**Comment by anguoyang** [comment]
@Dobiasd thank you, I have used the above script, it also generate the same error:
 raise ValueError('No model found in config file.')

**Comment by anguoyang** [comment]
I am sure the path is correct, I have copied the model file to the frugally-deep and also keras_export directory

**Comment by bobyguo** [comment]
@anguoyang Would you please check your Keras Version?

**Comment by anguoyang** [comment]
@Dobiasd @bobyguo I found the problem:)
the model saved with model.save_weights() not model.save()
I could not use the pre-trained model, I need to re-train and save it with model.save()
Thank you.

**Comment by anguoyang** [comment]
Is there any loading functions in keras that could load weights-only model file?

**Comment by Dobiasd** [comment]
Have a look into the [docs](https://keras.io/models/about-keras-models/). ;)
> `model.load_weights(filepath, by_name=False)`: loads the weights of the model from a HDF5 file (created by  save_weights). By default, the architecture is expected to be unchanged. To load weights into a different architecture (with some layers in common), use `by_name=True` to load only those layers with the same name.

**Comment by anguoyang** [comment]
@Dobiasd thank you, but this function need model to be initialized, 
model = load_model(in_path, custom_objects={'relu6': relu6})

**Comment by anguoyang** [comment]
https://stackoverflow.com/questions/47266383/save-and-load-weights-in-keras

**Comment by Dobiasd** [comment]
Sorry, I don't quite understand what you are trying to do and how the problem related to frugally-deep. Could you please explain further?

**Comment by anguoyang** [comment]
@Dobiasd I want to convert the .h5 model into json which could be used by frugally-deep. it seems that if the .h5 file has been saved with model.save(), then no problem, but if the saved with model.save_weights, then I could not use the convert tool in frugally-deep, I have to build the model first, and then load the weights, and then convert...

**Comment by Dobiasd** [comment]
Yes, that is correct. The weights alone are not sufficient. In order to use a model, the architecture (i.e. the computational graph) also has to be known.

Imagine you want to calculate the result of applying a function `f(x)`.
You know the function `f` has several variables in it, e.g. `f(x) = a * x*x + b * x + c` or `f(x) = 2 * x*x + 3 * b * x - c` This is the architecture of your model in this analogy.

To calculate a result of, let's say `f(42)` you also need to know the values of the variables, like:
`a = 12`, `b = 23`, `c = 34`. These are the weights in this analogy.

`x` (`42`) is the input value to the neural network in the analogy.

Now when you provide only the weights (i.e. the values for `a`, `b` and `c`) and an input `x`, this is not enough to actually calculate a result. The architecture, i.e. the actual formula of `f` needs to be known too.

When you are aware of this, it is very clear, why frugally-deep (and actually every other framework too) needs not only the weights, but also the models architecture to use if for any kind or computation. :)

In practice:
- `model.save()` saves the architecture and the weights
- `model.save_weights()` only saves the weights

In most normal use cases you only want to use `model.save()`. You only need `model.save_weights()` and `model.load_weights()` if you want to swap the architecture while re-using weights from a different model. This is needed if you want to fine-tune a conv-model with a different set of dense layers at the end of similar advanced stuff.
