### ISSUE TITLE
Question:Support for Deconv or TranposeConv

### ISSUE THREAD

**Issue by DianaLi96** [Dobiasd/frugally-deep#44]
May I ask if frugally-deep support the Deconv function or TansposeConv function?Thank you!

**Comment by Dobiasd** [comment]
[`keras.layers.Conv2DTranspose`](https://keras.io/layers/convolutional/#conv2dtranspose) currently is not supported, since it turns out a combination of [`UpSampling2D`](https://keras.io/layers/convolutional/#upsampling2d) and [`Conv2D`](https://keras.io/layers/convolutional/#conv2d) often works better. The following article goes more into the details: https://distill.pub/2016/deconv-checkerboard/
