### ISSUE TITLE
how can i use channels_first model in frugally lib

### ISSUE THREAD

**Issue by aligoglos** [Dobiasd/frugally-deep#60]
i have model that input shape is :
`[<tf.Tensor 'conv1_1_input:0' shape=(?, 1, 32, 32) dtype=float32>]`
and convert it to JSON with `convert_model.py`
but when i want load model according this line :
`const auto model = fdeep::load_model("eye_model.json");`
this error occur:
```
assertion(filter_mat.filter_shape_.depth_ == input.shape().depth_,
        "invalid filter depth");
```
because  filter_shape is` (1, 9, 9)` and input.shape is `(32, 1, 32)`.
i think because my model is first_channel  lib cant load correctly.
now how can i convert my model to channel last?
or is way to custom lib to load first_channel models?

**Comment by Dobiasd** [comment]
I'm wondering why `convert_model.py` allows to convert the model at all. It should raise an assertion error right at the start, see: https://github.com/Dobiasd/frugally-deep/blob/9ecdc9503b04c539954ec2589bb9e2396733d8aa/keras_export/convert_model.py#L477

Can you upload your model? (ideally with a minimal python code that generates it)

**Comment by Dobiasd** [comment]
Are you using different backend than TensorFlow or what is the reason behind explicitly setting `data_format='channels_first'` in your first layer?

If this is needed due to the format of your input, perhaps you can use [`numpy.rollaxis`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.rollaxis.html) on Python side?

In general frugally-deep only supports conversion of `channel_last` Keras models (even though it internally uses channel-first ordering internally on the C++ side).

**Comment by Dobiasd** [comment]
@aligoglos Since you closed [issue 63](https://github.com/Dobiasd/frugally-deep/issues/63), may I conclude that this one here is also to be considered as done?
