### ISSUE TITLE
Custom Keras Layers implementation how-to?

### ISSUE THREAD

**Issue by krworks** [Dobiasd/frugally-deep#61]
I would like to implement a custom layer in frugally deep so that it's recognized in the conversion (convert_model.py) and bound to code in frugally deep.  Is there a recommended way to go about this?  In this case, I am wanting to implement AnchorBoxes seen at:
https://github.com/pierluigiferrari/ssd_keras/blob/master/keras_layers/keras_layer_AnchorBoxes.py

I may be able to hack my way through this, but I was wondering if there was a sort of best practice.  Also if this is simply impossible for some reason that would be useful to know as well. :-)

**Comment by krworks** [comment]
Thus far it has been far simpler than I thought because this layer does not perform graph computations.  I merely have needed to change the following in convert_model.py
`model = load_model(in_path, custom_objects={'relu6': relu6})`
to
`model = load_model(in_path, custom_objects={'relu6': relu6, 'AnchorBoxes': AnchorBoxes})`
(as well as add the imports)
It's outputting a valid JSON now.  I'll close this right away once I get the same predictions out that I got in TensorFlow/Keras.

**Comment by krworks** [comment]
So it turns out that it does actually need to bind this layer at load time to something in frugally deep. I'm getting the error: unknown layer AnchorBoxes in frugally-deep. It's sort of obvious now, because of course this layer is clearly taking a tensor in and reshaping the data. However, I do see the code for associating the layer creators in import_model.hpp:
https://github.com/Dobiasd/frugally-deep/blob/a07f318b4bab5393ee1947c77d42ba9b1b5adcdc/include/fdeep/import_model.hpp#L773-L778

It doesn't seem terribly hard to do after-all.  I very much appreciate this library and I would like to thank you for making it.

**Comment by Dobiasd** [comment]
Hi krworks,

good job on understand the inner working of the library. :)

What you are trying to achieve reminds me of [issue 54](https://github.com/Dobiasd/frugally-deep/issues/54).
In general we can't easily transpile Python code to C++ code, so if you are using a custom Layer (lambda or not) in Keras, you would need to re-implement for forward pass of it in C++.

If I understand correctly, your solution involves making changes in the library (a bit in Python, more invasive stuff in C++) itself. Of course you can do it that way, but it could turn out to make your project a lot more cumbersome to maintain, because your private fork of frugally-deep makes it hard for you to update to future versions of from the master branch of it.

I wonder if you would be interested in the library supporting a universal way to inject custom layers into `fdeep::load_model` from client-code side as I proposed in [this comment](https://github.com/Dobiasd/frugally-deep/issues/54#issuecomment-393044777). What do you think?

**Comment by Dobiasd** [comment]
I guess we could solve the input-parameter problem for complex layers as follows:
- let the custom layer instance be constructed in client code, no matter how complex. Frugally-deep does not need to know anything about the parameters or initialization.
- wrap the forward pass into a single closure of type `std::function<fdeep::tensor3s(const fdeep::tensor3s&)>`
- pass this closure associated to the the appropriate name to `fdeep::load_model`.

So this solution would be the same as for lambda layers.

---

Regarding the inner workings of the AnchorBoxes layer: I'm sorry, but for me this is the first time I hear about it, so I can't explain it. :wink:

**Comment by Dobiasd** [comment]
Oh, I've missed that little detail. That makes it a bit more complicated. But you solution sounds reasonable.

Keep in mind that frugally-deep does not support a batch dimension. A layer takes a `fdeep::tensor3s` (i.e. `std::vector<fdeep::tensor3>`) as input not for batching, but because some layer types can take multiple tensors as input (and also output multiple tensors).

But `AnchorBoxes` effectively only takes (and returns) one tensor, so the implementation for the forward pass of it would probably use the following shapes:
```
input: one tensor3 of shape (channels, height, width)
output: one tensor3 of shape (height, width, n_boxes*8)
```

**Comment by krworks** [comment]
Forgive me for picking your brain here but wouldn't it be the case that I would have to now train with a batch size of 1 to support this library? I've got a successful 5D Tensor dump of the AnchorBoxes and all of the float data loaded in frugally deep at layer construction, and passed through in call.  I believe I can load / reshape it this way because the trainer simply computes a constant tensor which is used in constant form for all inputs (As far as I can tell, anyway).

The subsequent reshaping layer in the keras model reshapes the latter dimensions [n_boxes][8] to [n_boxes * 8] so I can just skip that step in the anchor layer to keep it compatible with frugally-deep.

However, with extra batch dimensions ([16]) is what confuses me. I cannot see it's possible use at forward pass other than losing much of the training input; or, if I reshape it in I would believe it would corrupt the results. Maybe I'm not thinking about this the right way at all, so forgive me because I'm a relative newcomer.  I've run forward passes with perfect results on a prior model I made but this one is far more complex.

Thank you for your feedback & advice on this so far.

**Comment by Dobiasd** [comment]
Oh, yes, if the `AnchorBoxes` is not the last one in your model, of course you will have problems with the following layers. You approach of combining `AnchorBoxes`+`Reshape` into one layer on Python side to then be able to emulate this layer in C++, currently seems like the best solution in this unpleasant scenario to me.

Without knowing much about the `AnchorBoxes` layer, I would not expect the batch dimension to be a problem. Other Keras layers also support batch processing during training and prediction. The shape of the trainable parameters of a layer should be independent of the `batch_size` used during training. In Keras you can train your model with `batch_size==32` for example but do your prediction forward passes with `batch_size==1`.

**Comment by mchijmma** [comment]
Hi Tobias,  

Thank you so much for providing this library, it's really good !

I have models that use various custom Convolutional and Lambda layers. Could you provide a short guide about how to extend frugally-deep in order to add your own layers.

For example, based on the generic Keras custom layer:

`from keras import backend as K
from keras.layers import Layer

class MyLayer(Layer):

    def __init__(self, output_dim, **kwargs):
        self.output_dim = output_dim
        super(MyLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        # Create a trainable weight variable for this layer.
        self.kernel = self.add_weight(name='kernel', 
                                      shape=(input_shape[1], self.output_dim),
                                      initializer='uniform',
                                      trainable=True)
        super(MyLayer, self).build(input_shape)  # Be sure to call this at the end

    def call(self, x):
        return K.dot(x, self.kernel)

    def compute_output_shape(self, input_shape):
        return (input_shape[0], self.output_dim)`

What would be the steps to incorporate MyLayer into frugally-deep ?

Many thanks !

**Comment by Dobiasd** [comment]
Hi Marco, thanks for the positive feedback. :)

> Could you provide a short guide about how to extend frugally-deep in order to add your own layers.

Currently frugally-deep does not yet support custom layers at all.

So the library would need to be extended with this functionality. Was this what you were talking about, i.e. offering to dive into this and create a pull request? Or did you hope for the feature to already be available and were looking for a short tutorial from a users perspective on how to use it?

**Comment by mchijmma** [comment]
I was thinking about cloning a fork locally and doing the changes on my machine. 

This, because I'm not sure if doing a merge would make sense since these layers that I'm planning to add are for quite specific applications (audio processing). 

Nevertheless, I would be happy to commit and push the changes to the fork and then create a PR.

Let me know if this make sense.

**Comment by Dobiasd** [comment]
Ah, OK, understood.

And I agree, your custom layers should not end up in the official frugally-deep repo.

So what you *could* do with your fork to add your layers is the following:
- Create a new layer class, inheriting from `fdeep::layer`, like [so](https://github.com/Dobiasd/frugally-deep/blob/e3e1a6a2e011ef6255d6589a5ec0981c9d0ef1f9/include/fdeep/layers/add_layer.hpp#L16).
- Create a new creator function for your layer type, like [so](https://github.com/Dobiasd/frugally-deep/blob/e3e1a6a2e011ef6255d6589a5ec0981c9d0ef1f9/include/fdeep/import_model.hpp#L594).
- Add your new creator function to the `creators` map in `create_layer`, like [so](https://github.com/Dobiasd/frugally-deep/blob/e3e1a6a2e011ef6255d6589a5ec0981c9d0ef1f9/include/fdeep/import_model.hpp#L1079).

However I feel you are buying in for some major pain in the future by doing so, because you basically freeze your frugally-deep version. So for future updates you have to decide between:
- Not profiting from new features, bug fixes, performance improvements etc. in the main version.
- Manually updating your version every time, tediously working forever like Sisyphus. :P

But I think we can have our cake and eat it too. :)

I will add a new parameter `custom_layer_creators` to `load_model`, of type
```cpp
const std::unordered_map<
    std::string,
    std::function<layer_ptr(
        const get_param_f&,
        const get_global_param_f&,
        const nlohmann::json&,
        const std::string&)>>&
```

It will be forwarded to `create_layer` and be used the same way as the creators for the build-in layer types.

This way you can inject your custom layer from user-code land, without needing to fork/modify the library.

The work to implement a custom layer will then be very similar to what I described above, i.e.:
- Create a new layer class, inheriting from `fdeep::layer`, like [so](https://github.com/Dobiasd/frugally-deep/blob/e3e1a6a2e011ef6255d6589a5ec0981c9d0ef1f9/include/fdeep/layers/add_layer.hpp#L16).
- Create a new creator function for your layer type, like [so](https://github.com/Dobiasd/frugally-deep/blob/e3e1a6a2e011ef6255d6589a5ec0981c9d0ef1f9/include/fdeep/import_model.hpp#L594)
- Pass a `custom_layer_creators` to `fdeep::load_model`, which maps layer names to your custom creators.

**Comment by Dobiasd** [comment]
@mchijmma: The implementation is ready. If you check out the latest version from master, you can use it to implement your custom layers in user-land code and inject their factories to `load_model`. :tada:

**Comment by mchijmma** [comment]
Oh that's great, thank you so much, `custom_layer_creators` it's a really clever solution !

**Comment by Detry322** [comment]
This is great! Thank you for adding this.
