### ISSUE TITLE
Predicted output did not match between C++ and Python

### ISSUE THREAD

**Issue by toannguyencnu** [Dobiasd/frugally-deep#72]
Hello, first of all, thank you very much for your library.
I am using your library for segmentation problems. 
I have been successful to convert trained model in Keras and load to C++. 
However, the prediction results in Python and C++ was not the same. I already check the input image and the first patch for prediction. Input values were same. Please help me to figure out the problems in my code. I would like to submit my codes, trained models and images here.
Best regards,
Toan Nguyen
Trained model and data can be found in the following link:

[https://drive.google.com/drive/folders/1_aHXL3Sr4FEisYFuaMMjo019EozmCP-Y](url)
Python Code
'def prediction_simple():
    model = load_model('test_best_weights.h5')
    # Load image from HDF5
    test_imgs_original = load_hdf5('DRIVE_dataset_imgs_test.hdf5')
    patch_h = 160
    patch_w = 160
    stride_h = 160
    stride_w = 160
    assert (len(test_imgs_original.shape)==4)  #4D arrays
    assert (test_imgs_original.shape[3]==1 or test_imgs_original.shape[3]==3)  #check the last channel is 1 or 3
    img_h = test_imgs_original.shape[1]  #height of the full image
    img_w = test_imgs_original.shape[2] #width of the full image
    assert ((img_h-patch_h)%stride_h==0 and (img_w-patch_w)%stride_w==0)
    N_patches_img = ((img_h-patch_h)//stride_h+1)*((img_w-patch_w)//stride_w+1)  #// --> division between integers
    N_patches_tot = N_patches_img*test_imgs_original.shape[0]
    patches = np.empty((N_patches_tot, patch_h, patch_w, test_imgs_original.shape[3]))
    iter_tot = 0
    #extract input image to patches
    for i in range(test_imgs_original.shape[0]):  #loop over the full images
        for h in range((img_h-patch_h)//stride_h+1):
            for w in range((img_w-patch_w)//stride_w+1):
                patch = test_imgs_original[i,h*stride_h:(h*stride_h)+patch_h,w*stride_w:(w*stride_w)+patch_w,:]
                patches[iter_tot]=patch
                iter_tot +=1   #total
    # Prediction
    predictions = model.predict(patches)  # , batch_size=32, verbose=2)
    input_1 = patches[0, :]
    print("1st input prediction = ")
    print(input_1)
    # Show prediction output
    output_1 = predictions[0, :]
    print("1st output prediction = ")
    print(output_1)

prediction_simple()'

C++ code in VS 2017
`#include "stdafx.h"
#include <iostream>
#define FDEEP_FLOAT_TYPE double
#include <fdeep/fdeep.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <time.h>
#include <boost/filesystem.hpp>
#include "stdlib.h"
using namespace std;
using namespace cv;
using cv::CLAHE;
string type2str(int type);

int main()
{
	cout << "Start program \n";
	// Load Pre-trained Model
	const auto model = fdeep::load_model("fdeep_model_test.json");
	cout << "input shape: \n";
	cout << fdeep::show_shape3s(model.get_input_shapes()) << endl;
	cout << "Load model completed \n";
	Mat image;
	string imageName("010.png");
	image = imread(imageName.c_str(), IMREAD_COLOR); // Read the file
	if (!image.data)                              // Check for invalid input
	{
		cout << "Could not open or find the image" << std::endl;
		return -1;
	}
	else
		cout << "Read OK" << endl;
	assert(image.isContinuous());
	// Show original image
	namedWindow("original image", WINDOW_AUTOSIZE);// Create a window for display.
	imshow("original image", image);                   // Show our image inside it.
	Mat grey_image, grey_image2;
	cvtColor(image, grey_image, COLOR_BGR2GRAY);
	//imshow("Grey Image", grey_image);
	//waitKey(1);
	// Convert to float
	grey_image.convertTo(grey_image, CV_32FC1);
	Mat crop_train, crop_test; // (300, 300, CV_8UC1);
	Rect rectCrop = Rect(0, 0, 160, 160);
	// Crop 1st patche
	crop_test = grey_image(rectCrop);
	crop_test.convertTo(crop_test, CV_8UC1);
	imshow("Croped Image", crop_test);
	waitKey(1);
	cout << "\n Crop_test image = " << endl << " " << crop_test << endl << endl;

	string ty = type2str(crop_test.type());
	printf("Matrix: %s %dx%d \n", ty.c_str(), crop_test.cols, crop_test.rows);

	// Croped image size
	cout << "Crop size 1: " << crop_test.cols << endl;
	cout << "Crop size 2: " << crop_test.rows << endl;

	// Predict with crop train image
	assert(crop_test.isContinuous());
	// convert cv::Mat to fdeep::tensor3(image1 to tensor)
	//const fdeep::tensor3 tensor_input = fdeep::tensor3_from_bytes(crop_test.ptr(), crop_test.rows, crop_test.cols, crop_test.channels() , 0.0f, 1.0f);
		const auto tensor_input = fdeep::tensor3_from_bytes(crop_test.ptr(),
		static_cast<std::size_t>(crop_test.rows),
		static_cast<std::size_t>(crop_test.cols),
		static_cast<std::size_t>(crop_test.channels())
		, 0.0f, 1.0f);
	assert(tensor_input.shape().depth_ == 1 || tensor_input.shape().depth_ == 3);
	const int mat_type = tensor_input.shape().depth_ == 1 ? CV_8UC1 : CV_8UC3;
	clock_t tStart = clock();
	const auto output_tensor = model.predict({ tensor_input });
	cout << "\n Predict output \n";
	std::cout << fdeep::show_tensor3s(output_tensor) << std::endl;

	printf("Prediction time: %.4fs\n", (double)(clock() - tStart) / CLOCKS_PER_SEC);
	const fdeep::tensor3s output_tensors = output_tensor;
	const fdeep::tensor3 output_tensor1 = output_tensors[0];
	const int mat_type2 = output_tensor1.shape().depth_ == 1 ? CV_8UC1 : CV_8UC3;
	const cv::Mat image3(cv::Size(output_tensor1.shape().width_, output_tensor1.shape().height_), mat_type2);
	fdeep::tensor3_into_bytes(output_tensor1, image3.data, image3.cols * image3.rows *image3.channels());
	cout << "\n Output predicted image value= " << endl << " " << image3 << endl << endl;
	cv::imshow("Prediction output", image3);
	waitKey(1);

	cout << "\n Predict completed \n";
	cout << "\nfinish\n";
	system("pause");
	return 0;
}`

**Comment by Dobiasd** [comment]
Thanks for reporting.

Could you please adjust your code example so that it is minimal but complete to reproduce the problem? ([ref1](http://sscce.org/), [ref2](https://stackoverflow.com/help/mcve)). I.e., remove everything that is not absolutely needed for the issue at hand, but don't leave important stuff out like for example the `import`s in the python code. Ideally I can just copy-paste your code into new `.py`/`.cpp` files, run/compile it and see the problem.

Also please [format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/) so that it becomes more readable.

**Comment by toannguyencnu** [comment]
Thank you very much for your quick response, 

These are my code for prediction:
I also added these code to the folder with others data files.
[here](https://drive.google.com/drive/folders/1_aHXL3Sr4FEisYFuaMMjo019EozmCP-Y)

Python code
`import numpy as np
import h5py

from keras.models import load_model
# Get training data
def load_hdf5(infile):
  with h5py.File(infile,"r") as f:  #"with" close the file after its nested commands
    return f["image"][()]
patch_h = 160
patch_w = 160
stride_h = 160
stride_w = 160
# Load Model
model = load_model('test_best_weights.h5')
# Load image from HDF5
test_imgs_original = load_hdf5('DRIVE_dataset_imgs_test.hdf5')
assert (len(test_imgs_original.shape)==4)  #4D arrays
assert (test_imgs_original.shape[3]==1 or test_imgs_original.shape[3]==3)  #check the last channel is 1 or 3
img_h = test_imgs_original.shape[1]  #height of the full image
img_w = test_imgs_original.shape[2] #width of the full image
assert ((img_h-patch_h)%stride_h==0 and (img_w-patch_w)%stride_w==0)
N_patches_img = ((img_h-patch_h)//stride_h+1)*((img_w-patch_w)//stride_w+1)  #// --> division between integers
N_patches_tot = N_patches_img*test_imgs_original.shape[0]
patches = np.empty((N_patches_tot, patch_h, patch_w, test_imgs_original.shape[3]))
iter_tot = 0
#extract input image to patches
for i in range(test_imgs_original.shape[0]):  #loop over the full images
    for h in range((img_h-patch_h)//stride_h+1):
        for w in range((img_w-patch_w)//stride_w+1):
            patch = test_imgs_original[i,h*stride_h:(h*stride_h)+patch_h,w*stride_w:(w*stride_w)+patch_w,:]
            patches[iter_tot]=patch
            iter_tot +=1   #total
# Prediction
predictions = model.predict(patches)  # , batch_size=32, verbose=2)
input_1 = patches[0, :]
print("1st input prediction = ")
print(input_1)
# Show prediction output
output_1 = predictions[0, :]
print("1st output prediction = ")
print(output_1)`

C++ code
`
#include "stdafx.h"
#include <iostream>
#define FDEEP_FLOAT_TYPE double
#include <fdeep/fdeep.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <time.h>
#include <boost/filesystem.hpp>
#include "stdlib.h"
using namespace std;
using namespace cv;
using cv::CLAHE;
string type2str(int type);
int main()
{
	// Load Pre-trained Model
	const auto model = fdeep::load_model("fdeep_model_test.json");
	cout << "input shape: \n";
	cout << fdeep::show_shape3s(model.get_input_shapes()) << endl;
	Mat image;
	string imageName("010.png");
	image = imread(imageName.c_str(), IMREAD_COLOR); // Read the file
	if (!image.data)                              // Check for invalid input
	{
		cout << "Could not open or find the image" << std::endl;
		return -1;
	}
	else
		cout << "Read OK" << endl;
	assert(image.isContinuous());
	// Show original image
	namedWindow("original image", WINDOW_AUTOSIZE);// Create a window for display.
	imshow("original image", image);                   // Show our image inside it.
	Mat grey_image, grey_image2;
	cvtColor(image, grey_image, COLOR_BGR2GRAY);
	//imshow("Grey Image", grey_image);
	//waitKey(1);
	// Convert to float
	grey_image.convertTo(grey_image, CV_32FC1);
	Mat crop_train, crop_test; // (300, 300, CV_8UC1);
	Rect rectCrop = Rect(0, 0, 160, 160);
	// Crop 1st patche
	crop_test = grey_image(rectCrop);
	crop_test.convertTo(crop_test, CV_8UC1);
	imshow("Croped Image", crop_test);
	waitKey(1);
	cout << "\n Input_prediction = " << endl << " " << crop_test << endl << endl;
	assert(crop_test.isContinuous());
	const auto tensor_input = fdeep::tensor3_from_bytes(crop_test.ptr(),
	static_cast<std::size_t>(crop_test.rows),
	static_cast<std::size_t>(crop_test.cols),
	static_cast<std::size_t>(crop_test.channels())
	, 0.0f, 1.0f);
	assert(tensor_input.shape().depth_ == 1 || tensor_input.shape().depth_ == 3);
	const int mat_type = tensor_input.shape().depth_ == 1 ? CV_8UC1 : CV_8UC3;
	clock_t tStart = clock();
	const auto output_tensor = model.predict({ tensor_input });
	cout << "\n Predict output \n";
	std::cout << fdeep::show_tensor3s(output_tensor) << std::endl;
	printf("Prediction time: %.4fs\n", (double)(clock() - tStart) / CLOCKS_PER_SEC);
	const fdeep::tensor3s output_tensors = output_tensor;
	const fdeep::tensor3 output_tensor1 = output_tensors[0];
	const int mat_type2 = output_tensor1.shape().depth_ == 1 ? CV_8UC1 : CV_8UC3;
	const cv::Mat image3(cv::Size(output_tensor1.shape().width_, output_tensor1.shape().height_), mat_type2);
	fdeep::tensor3_into_bytes(output_tensor1, image3.data, image3.cols * image3.rows *image3.channels());
	cout << "\n Output predicted image value= " << endl << " " << image3 << endl << endl;
	cv::imshow("Prediction output", image3);
	waitKey(1);
	cout << "\n Predict completed \n";
	system("pause");
	return 0;
}
`

**Comment by Dobiasd** [comment]
Sorry, but this example is everything but minimal. I was able to compile and run the C++ code you uploaded to Google Drive (after removing some strange invisible whitespace characters). It prints a huge block of numbers into the terminal, opens an image window and closes it immediately. Sure, I could now clean up your code myself, understand what it is supposed to do, find out what is supposed to happen instead and to compare these two things. However I feel that this is your job, not mine. Some things I would expect at least:
- Remove superfluous stuff like the include of `boost/filesystem.hpp`, the Contrast-Limited-Adaptive-histogram-equalization-using directive.
- Don't use non-portable stuff like `system("pause");`. You can have the same effect with `waitKey(0);` instead.
- Use correct indentation (e.g., for the muli-line function call)
- Remove all stuff that is not needed to show the actual problem. For example you say the problem is incorrect results, not performance. So remove all performance-measuring code, commented-out code etc.

But the most important thing would be to provide a concise description of:
- the steps you take
- the results you get
- the results you expect instead

Please read [sscce](http://sscce.org/) and [mcve](https://stackoverflow.com/help/mcve)).

**Comment by Dobiasd** [comment]
Thanks, I appreciate your effort in trying to clean things up and create an minimal example. However it was not really minimal and took some effort on my side to make an actual minimal thing of it to see the essence of the problem. But to speed the process up, I did it nonetheless. :wink: Here it is:

```python
# minimal.py
# run: python3 minimal.py

from keras.models import load_model
from PIL import Image
import numpy as np

model = load_model('test_best_weights.h5')
input_image = Image.open('input.png')
input_tensors = np.array(input_image, np.float32).reshape(1, 160, 160, 1)
output_tensor = model.predict(input_tensors)[0]
output_image = Image.fromarray((output_tensor * 255.0).reshape(160, 160).astype(np.uint8))
output_image.save('output_python.png')
```

```cpp
// minimal_err.cpp
// compile and run: g++ -std=c++14 -O3 minimal_err.cpp -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -lopencv_highgui -o minimal_err && ./minimal_err

#define FDEEP_FLOAT_TYPE double
#include <fdeep/fdeep.hpp>
#include <opencv2/highgui/highgui.hpp>

int main()
{
    const fdeep::model model = fdeep::load_model("fdeep_model_test.json");
    const cv::Mat input_image = cv::imread("input.png", cv::IMREAD_GRAYSCALE);
    const fdeep::tensor3 input_tensor = fdeep::tensor3_from_bytes(input_image.ptr(),
        static_cast<std::size_t>(input_image.rows),
        static_cast<std::size_t>(input_image.cols),
        static_cast<std::size_t>(input_image.channels()));

    const fdeep::tensor3 tensor_output = model.predict({ input_tensor })[0];

    cv::Mat output_image(tensor_output.shape().height_, tensor_output.shape().width_, CV_8UC1);
    fdeep::tensor3_into_bytes(tensor_output, output_image.ptr(),
        output_image.cols * output_image.rows * output_image.channels(),
        0.0, 1.0);
    cv::imwrite("output_cpp_err.png", output_image);
}
```

(removed all the cropping stuff that has nothing to do with the actual prediction problem)


And here are the corresponding images:

`input.png`:
![image](https://i.imgur.com/wEc6L58.png)

`output_python.png`:
![image](https://i.imgur.com/1oFe7V3.png)

`output_cpp_err.png`:
![image](https://i.imgur.com/PFXtnjD.png)

So this setup reproduces your problem exactly.

---

OK, so why the difference?

When you are printing out the tensor values in your code, you are not printing what you actually provide to `model.predict`, i.e., `tensor_input` in your case, but `crop_test` instead. `crop_test` however goes into `tensor3_from_bytes` to create the values of `tensor_input`.

Having a look at the documentation of `tensor3_from_bytes` shows that it scales the values:

```cpp
// Converts a memory block holding 8-bit values into a tensor3.
// Data must be stored row-wise (and channels_last).
// Scales the values from range [0, 255] into [low, high].
// May be used to convert an image (bgr, rgba, gray, etc.) to a tensor3.
inline tensor3 tensor3_from_bytes(const std::uint8_t* value_ptr,
    std::size_t height, std::size_t width, std::size_t channels,
    internal::float_type low = 0.0f, internal::float_type high = 1.0f);
```

It does this by default, since usually one trains models with [0.0 1.0], not with [0, 255].

But your model obviously is trained with [0, 255]. You Python code shows this, because you are not doing that scaling into [0.0 1.0]. Instead the value are used in the original scale [0, 255] for predictions of the model (which is totally OK if it works).

(But This is why I recommend creating actual minimal examples so much. The difference is much easier to spot then.)

So, let's adjust the C++ code to leave the values in range [0, 255] here too:

```cpp
// minimal_ok.cpp
// compile and run: g++ -std=c++14 -O3 minimal_ok.cpp -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -lopencv_highgui -o minimal_ok && ./minimal_ok

#define FDEEP_FLOAT_TYPE double
#include <fdeep/fdeep.hpp>
#include <opencv2/highgui/highgui.hpp>

int main()
{
    const fdeep::model model = fdeep::load_model("fdeep_model_test.json");
    const cv::Mat input_image = cv::imread("input.png", cv::IMREAD_GRAYSCALE);
    const fdeep::tensor3 input_tensor = fdeep::tensor3_from_bytes(input_image.ptr(),
        static_cast<std::size_t>(input_image.rows),
        static_cast<std::size_t>(input_image.cols),
        static_cast<std::size_t>(input_image.channels()),
        0.0, 255.0);

    const fdeep::tensor3 tensor_output = model.predict({ input_tensor })[0];

    cv::Mat output_image(tensor_output.shape().height_, tensor_output.shape().width_, CV_8UC1);
    fdeep::tensor3_into_bytes(tensor_output, output_image.ptr(),
        output_image.cols * output_image.rows * output_image.channels(),
        0.0, 1.0);
    cv::imwrite("output_cpp_ok.png", output_image);
}
```

And, yeah, we have the correct result:

`output_cpp_ok.png`:
![image](https://i.imgur.com/b8EBoTy.png)

:)
