### ISSUE TITLE
Keras 'predict_proba' feature in frugally-deep.

### ISSUE THREAD

**Issue by Aghabeiki** [Dobiasd/frugally-deep#81]
Sorry to open it again, But I think it's not just for backward-compatibility,
based Keras docs.
It's a very useful function in classification, exactly when we have more than one runs in our ML output,

As explained here :

    def predict_proba(self, x, batch_size=32, verbose=0):
        """Generates class probability predictions for the input samples.
        The input samples are processed batch by batch.
        # Arguments
            x: input data, as a Numpy array or list of Numpy arrays
                (if the model has multiple inputs).
            batch_size: integer.
            verbose: verbosity mode, 0 or 1.
        # Returns
            A Numpy array of probability predictions.
        """
Conclusion: fdeep::model::predict_class should be the thing that I need if it returns all the activation value not just the maximum index.

**Comment by Dobiasd** [comment]
Using the [old issue](https://github.com/Dobiasd/frugally-deep/issues/80#issuecomment-414185297) for this follow-up would have been nice, but OK, here we are with a second issue for this topic. :wink:

OK, to the actual question: `model.predict_proba` is the same as `model.predict`. 
Here is a minimal example showing this:

```python
import numpy as np
from keras.layers import Dense
from keras.models import Sequential
import keras

model = Sequential()
model.add(Dense(5, activation='relu', input_shape=(4,)))
model.add(Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='nadam')

model.fit(
    np.asarray([[1,2,3,4], [2,3,4,5]]),
    np.asarray([[1,0,0], [0,0,1]]), epochs=10)

print(keras.__version__)
print(model.predict(np.asarray([[3,4,5,6]])))
print(model.predict_proba(np.asarray([[3,4,5,6]])))
```

Output:
```
2.2.0
[[3.5037649e-06 5.9615293e-05 9.9993682e-01]]
[[3.5037649e-06 5.9615293e-05 9.9993682e-01]]
```

If you look into the [actual code](https://github.com/keras-team/keras/blob/7205d903fbc079bb99fbae0e3c02e6d2b4d227f0/keras/engine/sequential.py#L245-L251) of the sequential model implementation, you see:
```python
def predict_proba(self, x, batch_size=32, verbose=0):
    # ...
    preds = self.predict(x, batch_size, verbose)
    # ...
    return preds
```

So `predict_proba` just forwards` the call to `predict` and is only there for backward-compatibility reasons as explained in this [stackoverflow thread](https://stackoverflow.com/questions/40747679/keras-what-is-the-difference-between-model-predict-and-model-predict-proba).

If you try it with a [functional model instead of a sequential one](https://gist.github.com/Dobiasd/724cb1a35e504886feb53c0ec4073862), you will even get `AttributeError: 'Model' object has no attribute 'predict_proba'`.

So, conclusion: `predict` and `predict_proba` in Keras are the same. `fdeep::model::predict` is what you are looking for, and there is no reason to implement a redundant `fdeep::model::predict_class`.
