### ISSUE TITLE
Invalid shape of bias matrix for GRU inside Bidirectional

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/frugally-deep#99]
When setting `use_bias=True` for a `GRU` layer in a `Bidirectional` layer, we end up with `ERROR: invalid shape` in the C++ part.

---

Steps to quickly reproduce:

In `get_test_model_recurrent` in `generate_test_models.py` change:

```python
    gru2 = Bidirectional(
        GRU(
            units=6,
            recurrent_activation='hard_sigmoid',
            reset_after=False,
            return_sequences=True,
            use_bias=False
        )
    )(gru1)
```

to

```python
    gru2 = Bidirectional(
        GRU(
            units=6,
            recurrent_activation='hard_sigmoid',
            reset_after=False,
            return_sequences=True,
            use_bias=True
        )
    )(gru1)
```

then:

```bash
cd build
python3 ../keras_export/generate_test_models.py recurrent test_model_recurrent.h5
python3 ../keras_export/convert_model.py test_model_recurrent.h5 test_model_recurrent.json
cd .. && g++ -Iinclude -lpthread -DNDEBUG -mavx -O3 -std=c++14 -Wall -Wextra -pedantic -Wshadow -Werror -Weffc++ -Wconversion -Wsign-conversion -Wctor-dtor-privacy -Wreorder -Wold-style-cast test/applications_performance.cpp -o build/applications_performance && cd build
./applications_performance
```

**Comment by hunyadi** [comment]
I am including my comment from the other thread, to keep everything in one place. (Numbers adjusted to correspond to the example in this issue.)

Below is what I get when I inspect the HDF5 file directly (produced by `generate_test_models.py`) for two cases: one without a bidirectional wrapper and one with such a wrapper:
```
>>> f['model_weights']['gru_1']['gru_1']['bias:0']
<HDF5 dataset "bias:0": shape (2, 18), type "<f4">
>>> f['model_weights']['bidirectional_4']['bidirectional_4']['forward_gru_2']['bias:0']
<HDF5 dataset "bias:0": shape (18,), type "<f4">
```
The first item corresponds to a regular GRU layer with 6 units; the bias matrix has the expected shape of [2,18] where 18 = 3 * _number of units_ = 3 * 6. The second item is a bidirectional GRU layer with 6 units, and the bias matrix appears to have lost a row: it should have a shape of [2,18] where 18 = 3 * 6 but it turns out to be a vector rather than a matrix in HDF5.

We should check what the Keras reconstitution rules are for a bidirectional layer. Perhaps we might recover the bias matrix for both forward and backward GRU layers using `forward_bias` and `backward_bias` if the missing part of one is a transformation of the other. This might be done either in the Python (upon conversion) or the C++ layer (upon instantiation).

**Comment by n-Guard** [comment]
I don't if this is any new information, but when `reset_after=False`, there is apparently no recurrent bias:
https://github.com/keras-team/keras/blob/8a73aec637a853f0fccb544dcb61dfe170db1277/keras/layers/recurrent.py#L1295-L1296

**Comment by hunyadi** [comment]
New information to me, but it also makes it easy to close this issue. Currently, the C++ code uses a _bias_ matrix, but it seems it should instead use a _kernel_bias_ vector and a _recurrent_kernel_bias_ vector, and not use the _recurrent_kernel_bias_ vector at all when `reset_after=False` (i.e. the original TensorFlow case, not the CuDNN case).

I am out of work and will not be able to make the change today or over the weekend but if no-one takes on this issue until Monday, I can open a pull request with this minor change.

**Comment by Dobiasd** [comment]
Thanks @hunyadi for [the fix](https://github.com/Dobiasd/frugally-deep/pull/103).

And also thanks @n-Guard for this very helpful hint.
